// src-react-backup/pages/Participants.js
import React, { useState, useEffect } from 'react';
import { 
  Search, 
  Filter, 
  Users, 
  Mail, 
  Phone, 
  Calendar, 
  MapPin, 
  Loader2
} from 'lucide-react';
import { eventsService } from '../services/eventsService';
import { auth } from '../lib/supabase';
import { useNavigate } from 'react-router-dom';
import { canManageParticipants } from '../services/roleService';

const Participants = () => {
  const navigate = useNavigate();
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedEvent, setSelectedEvent] = useState('all');
  const [selectedStatus, setSelectedStatus] = useState('all');
  const [participants, setParticipants] = useState([]);
  const [events, setEvents] = useState([]);
  const [statuses, setStatuses] = useState(['all', 'registered', 'attended', 'cancelled']);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [user, setUser] = useState(null);

  // Load data on component mount
  useEffect(() => {
    const loadData = async () => {
      try {
        setLoading(true);
        
        // Get current user
        const { user, error: authError } = await auth.getCurrentUser();
        if (authError || !user) {
          navigate('/login');
          return;
        }
        setUser(user);

        // Check if user can manage participants
        if (!canManageParticipants(user)) {
          setError('You need to be an Event Organizer to manage participants');
          setLoading(false);
          return;
        }

        // Load events for filter dropdown
        const { data: eventsData, error: eventsError } = await eventsService.getAllEvents();
        if (eventsError) throw eventsError;
        
        const eventsList = [
          { id: 'all', name: 'All Events' },
          ...eventsData.map(event => ({ id: event.id, name: event.title }))
        ];
        setEvents(eventsList);

        // Load available statuses
        const { data: statusList, error: statusError } = await eventsService.getParticipantStatuses();
        if (!statusError && statusList) {
          setStatuses(statusList);
        }

        // Load participants data
        await loadParticipants();

      } catch (error) {
        console.error('Error loading data:', error);
        setError('Failed to load data. Please try again.');
      } finally {
        setLoading(false);
      }
    };

    loadData();
  }, [navigate]);


  // Load participants from database
  const loadParticipants = async () => {
    try {
      // Get all events first
      const { data: eventsData, error: eventsError } = await eventsService.getAllEvents();
      if (eventsError) {
        throw eventsError;
      }

      if (!eventsData || eventsData.length === 0) {
        setParticipants([]);
        return;
      }

      const participantMap = new Map(); // To avoid duplicates

      // For each event, get its participants
      for (const event of eventsData) {
        const { data: participantDetails, error: detailsError } = await eventsService.getEventParticipantsDetails(event.id);
        
        if (detailsError) {
          continue;
        }

        // Add participants to our list (avoiding duplicates)
        if (participantDetails && participantDetails.length > 0) {
          participantDetails.forEach((participant) => {
            // Validate required fields
            if (!participant.first_name || !participant.last_name) {
              return; // Skip this participant
            }
            
            const key = `${participant.user_id}-${participant.event_id}`;
            if (!participantMap.has(key)) {
              const participantObj = {
                id: participant.id,
                user_id: participant.user_id,
                first_name: participant.first_name,
                last_name: participant.last_name,
                email: participant.email || 'No email',
                phone: participant.phone || 'No phone',
                event_id: participant.event_id,
                event_title: event.title,
                registration_date: participant.created_at || participant.updated_at || new Date().toISOString(),
                status: participant.status || 'registered' // Use actual status from database
              };
              
              participantMap.set(key, participantObj);
            }
          });
        }
      }

      const participantsList = Array.from(participantMap.values());
      setParticipants(participantsList);
    } catch (error) {
      setError('Failed to load participants. Please try again.');
    }
  };

  const filteredParticipants = (participants || []).filter(participant => {
    const fullName = `${participant.first_name || ''} ${participant.last_name || ''}`.toLowerCase();
    const email = participant.email || '';
    const matchesSearch = fullName.includes(searchQuery.toLowerCase()) ||
                         email.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesEvent = selectedEvent === 'all' || participant.event_id === selectedEvent;
    const matchesStatus = selectedStatus === 'all' || participant.status === selectedStatus;
    
    return matchesSearch && matchesEvent && matchesStatus;
  });

  const getStatusColor = (status) => {
    switch (status?.toLowerCase()) {
      case 'attended': return 'bg-green-100 text-green-800';
      case 'registered': return 'bg-blue-100 text-blue-800';
      case 'pending': return 'bg-yellow-100 text-yellow-800';
      case 'cancelled': return 'bg-red-100 text-red-800';
      case 'active': return 'bg-green-100 text-green-800'; // Legacy support
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  return (
    <div className="space-y-4 sm:space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4">
        <div className="min-w-0">
          <h1 className="text-2xl sm:text-3xl font-bold text-gray-900">Participants</h1>
          <p className="text-sm sm:text-base text-gray-600 mt-1">Manage and engage with event participants</p>
        </div>
      </div>

      {/* Loading State */}
      {loading && (
        <div className="flex items-center justify-center min-h-96">
          <div className="text-center">
            <Loader2 className="h-8 w-8 animate-spin mx-auto mb-4 text-primary-600" />
            <p className="text-gray-600">Loading participants...</p>
          </div>
        </div>
      )}

      {/* Error State */}
      {error && (
        <div className="bg-red-50 border border-red-200 rounded-lg p-6">
          <div className="text-center">
            <h3 className="text-lg font-medium text-red-900 mb-2">Error Loading Participants</h3>
            <p className="text-red-600 mb-4">{error}</p>
            <button 
              onClick={() => window.location.reload()} 
              className="btn-primary"
            >
              Try Again
            </button>
          </div>
        </div>
      )}

      {/* Main Content */}
      {!loading && !error && (
        <>
      {/* Participant Statistics */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 sm:gap-6">
        <div className="card text-center p-4 sm:p-6">
          <div className="p-2 sm:p-3 bg-blue-100 rounded-full w-12 h-12 sm:w-16 sm:h-16 mx-auto mb-2 sm:mb-4 flex items-center justify-center">
            <Users className="text-blue-600" size={24} />
          </div>
          <h3 className="text-xl sm:text-2xl font-bold text-gray-900 mb-1 sm:mb-2">{participants?.length || 0}</h3>
          <p className="text-xs sm:text-sm text-gray-600">Total</p>
        </div>

        <div className="card text-center p-4 sm:p-6">
          <div className="p-2 sm:p-3 bg-green-100 rounded-full w-12 h-12 sm:w-16 sm:h-16 mx-auto mb-2 sm:mb-4 flex items-center justify-center">
            <Users className="text-green-600" size={24} />
          </div>
          <h3 className="text-xl sm:text-2xl font-bold text-gray-900 mb-1 sm:mb-2">
            {(participants || []).filter(p => p.status === 'attended' || p.status === 'active').length}
          </h3>
          <p className="text-xs sm:text-sm text-gray-600">Attended</p>
        </div>

        <div className="card text-center p-4 sm:p-6">
          <div className="p-2 sm:p-3 bg-blue-100 rounded-full w-12 h-12 sm:w-16 sm:h-16 mx-auto mb-2 sm:mb-4 flex items-center justify-center">
            <Users className="text-blue-600" size={24} />
          </div>
          <h3 className="text-xl sm:text-2xl font-bold text-gray-900 mb-1 sm:mb-2">
            {(participants || []).filter(p => p.status === 'registered').length}
          </h3>
          <p className="text-xs sm:text-sm text-gray-600">Registered</p>
        </div>

        <div className="card text-center p-4 sm:p-6">
          <div className="p-2 sm:p-3 bg-purple-100 rounded-full w-12 h-12 sm:w-16 sm:h-16 mx-auto mb-2 sm:mb-4 flex items-center justify-center">
            <Calendar className="text-purple-600" size={24} />
          </div>
          <h3 className="text-xl sm:text-2xl font-bold text-gray-900 mb-1 sm:mb-2">
            {(participants || []).filter(p => p.events?.length > 1).length}
          </h3>
          <p className="text-xs sm:text-sm text-gray-600">Multi-Event</p>
        </div>
      </div>

      {/* Filters and Search */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-4 sm:p-6">
        <div className="flex flex-col gap-3 sm:gap-4">
          {/* Search */}
          <div className="w-full">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" size={18} />
              <input
                type="text"
                placeholder="Search by name or email..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-10 pr-4 py-2 text-sm sm:text-base border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent"
              />
            </div>
          </div>

          {/* Filters Row */}
          <div className="flex flex-col sm:flex-row gap-3 sm:gap-4">
            {/* Event Filter */}
            <div className="flex-1 sm:flex-initial sm:w-44 lg:w-48">
              <select
                value={selectedEvent}
                onChange={(e) => setSelectedEvent(e.target.value)}
                className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent"
              >
                {events.map(event => (
                  <option key={event.id} value={event.id}>{event.name}</option>
                ))}
              </select>
            </div>

            {/* Status Filter */}
            <div className="flex-1 sm:flex-initial sm:w-44 lg:w-48">
              <select
                value={selectedStatus}
                onChange={(e) => setSelectedStatus(e.target.value)}
                className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent"
              >
                {statuses.map(status => (
                  <option key={status} value={status}>
                    {status === 'all' ? 'All Status' : status.charAt(0).toUpperCase() + status.slice(1)}
                  </option>
                ))}
              </select>
            </div>
          </div>
        </div>
      </div>

      {/* Participants List */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Participant</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Contact</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Events</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Registration</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {filteredParticipants.map((participant) => (
                <tr key={participant.id} className="hover:bg-gray-50">
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="flex items-center">
                      <div className="w-10 h-10 rounded-full mr-4 bg-primary-100 flex items-center justify-center">
                        <span className="text-primary-600 font-semibold text-sm">
                          {participant.first_name.charAt(0)}{participant.last_name.charAt(0)}
                        </span>
                      </div>
                      <div>
                        <div className="text-sm font-medium text-gray-900">
                          {participant.first_name} {participant.last_name}
                        </div>
                        <div className="text-sm text-gray-500">ID: {participant.id}</div>
                      </div>
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="text-sm text-gray-900">{participant.email}</div>
                    <div className="text-sm text-gray-500">{participant.phone || 'No phone'}</div>
                  </td>
                  <td className="px-6 py-4">
                    <div className="text-sm text-gray-900">
                      <span className="inline-flex items-center px-2 py-1 rounded-full text-xs bg-blue-100 text-blue-800">
                        {participant.event_title}
                      </span>
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                    <div>{new Date(participant.registration_date).toLocaleDateString()}</div>
                    <div className="text-gray-500">Registered</div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${getStatusColor(participant.status)}`}>
                      {participant.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Empty State */}
      {(filteredParticipants?.length || 0) === 0 && (
        <div className="text-center py-12">
          <div className="text-gray-400 mb-4">
            <Users size={64} className="mx-auto" />
          </div>
          <h3 className="text-lg font-medium text-gray-900 mb-2">No participants found</h3>
          <p className="text-gray-500 mb-6">Try adjusting your search or filter criteria</p>
        </div>
      )}
        </>
      )}
    </div>
  );
};

export default Participants;

// src/app/features/events/pages/participants/participants.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../../../core/services/auth.service';
import { EventsService } from '../../../../core/services/events.service';
import { RoleService } from '../../../../core/services/role.service';

interface Participant {
  id: string;
  user_id: string;
  first_name: string;
  last_name: string;
  email: string;
  phone?: string;
  event_id: string;
  event_title: string;
  registration_date: string;
  status: string;
}

@Component({
  selector: 'app-participants',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './participants.component.html',
  styleUrl: './participants.component.css'
})
export class ParticipantsComponent implements OnInit {
  // Data
  searchQuery = '';
  selectedEvent = 'all';
  selectedStatus = 'all';
  participants: Participant[] = [];
  events: any[] = [];
  statuses = ['all', 'registered', 'attended', 'cancelled'];
  loading = true;
  error: string | null = null;
  user: any = null;

  constructor(
    private router: Router,
    private authService: AuthService,
    private eventsService: EventsService,
    private roleService: RoleService
  ) { }

  async ngOnInit() {
    await this.loadData();
  }

  async loadData() {
    try {
      this.loading = true;

      this.user = await this.authService.getCurrentUser();
      if (!this.user) {
        this.router.navigate(['/login']);
        return;
      }

      if (!this.roleService.canManageParticipants(this.user)) {
        this.error = 'You need to be an Event Organizer to manage participants';
        this.loading = false;
        return;
      }

      const { data: eventsData } = await this.eventsService.getAllEvents();
      this.events = [
        { id: 'all', title: 'All Events' },
        ...(eventsData || [])
      ];

      await this.loadParticipants();

    } catch (error: any) {
      console.error('Error loading data:', error);
      this.error = 'Failed to load data. Please try again.';
    } finally {
      this.loading = false;
    }
  }

  async loadParticipants() {
    try {
      const { data: eventsData } = await this.eventsService.getAllEvents();

      if (!eventsData || eventsData.length === 0) {
        this.participants = [];
        return;
      }

      const participantMap = new Map<string, Participant>();

      for (const event of eventsData) {
        const { data: participantDetails } = await this.eventsService.getEventParticipantsDetails(event.id);

        if (participantDetails && participantDetails.length > 0) {
          participantDetails.forEach((participant: any) => {
            if (!participant.first_name || !participant.last_name) return;

            const key = `${participant.user_id}-${participant.event_id}`;
            if (!participantMap.has(key)) {
              participantMap.set(key, {
                id: participant.id,
                user_id: participant.user_id,
                first_name: participant.first_name,
                last_name: participant.last_name,
                email: participant.email || 'No email',
                phone: participant.phone,
                event_id: participant.event_id,
                event_title: event.title,
                registration_date: participant.created_at || new Date().toISOString(),
                status: participant.status || 'registered'
              });
            }
          });
        }
      }

      this.participants = Array.from(participantMap.values());
    } catch (error) {
      console.error('Error loading participants:', error);
      this.error = 'Failed to load participants. Please try again.';
    }
  }

  get filteredParticipants(): Participant[] {
    return this.participants.filter(participant => {
      const fullName = `${participant.first_name} ${participant.last_name}`.toLowerCase();
      const matchesSearch = fullName.includes(this.searchQuery.toLowerCase()) ||
        participant.email.toLowerCase().includes(this.searchQuery.toLowerCase());
      const matchesEvent = this.selectedEvent === 'all' || participant.event_id === this.selectedEvent;
      const matchesStatus = this.selectedStatus === 'all' || participant.status === this.selectedStatus;

      return matchesSearch && matchesEvent && matchesStatus;
    });
  }

  get totalParticipants(): number {
    return this.participants.length;
  }

  get attendedCount(): number {
    return this.participants.filter(p => p.status === 'attended').length;
  }

  get registeredCount(): number {
    return this.participants.filter(p => p.status === 'registered').length;
  }

  getStatusColor(status: string): string {
    switch (status?.toLowerCase()) {
      case 'attended': return 'bg-green-100 text-green-800';
      case 'registered': return 'bg-blue-100 text-blue-800';
      case 'pending': return 'bg-yellow-100 text-yellow-800';
      case 'cancelled': return 'bg-red-100 text-red-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  }

  onSearchChange(event: Event) {
    this.searchQuery = (event.target as HTMLInputElement).value;
  }

  onEventFilterChange(event: Event) {
    this.selectedEvent = (event.target as HTMLSelectElement).value;
  }

  onStatusFilterChange(event: Event) {
    this.selectedStatus = (event.target as HTMLSelectElement).value;
  }
}

<!-- Loading State -->
<div *ngIf="loading" class="flex items-center justify-center min-h-96">
    <div class="text-center">
        <div class="animate-spin h-8 w-8 border-4 border-primary-600 border-t-transparent rounded-full mx-auto mb-4">
        </div>
        <p class="text-gray-600">Loading participants...</p>
    </div>
</div>

<!-- Error State -->
<div *ngIf="error" class="bg-red-50 border border-red-200 rounded-lg p-6">
    <div class="text-center">
        <h3 class="text-lg font-medium text-red-900 mb-2">Error Loading Participants</h3>
        <p class="text-red-600 mb-4">{{ error }}</p>
        <button (click)="loadData()" class="action-btn primary">Try Again</button>
    </div>
</div>

<!-- Main Content -->
<div *ngIf="!loading && !error">
    <!-- Statistics -->
    <div class="stats-grid mb-6">
        <div class="stat-card blue">
            <div class="stat-icon">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
                    <path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2" stroke="currentColor" stroke-width="2" />
                    <circle cx="9" cy="7" r="4" stroke="currentColor" stroke-width="2" />
                </svg>
            </div>
            <div class="stat-info">
                <div class="stat-label">Total Participants</div>
                <div class="stat-value">{{ totalParticipants }}</div>
            </div>
        </div>
        <div class="stat-card green">
            <div class="stat-icon">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
                    <path d="M22 11.08V12a10 10 0 11-5.93-9.14" stroke="currentColor" stroke-width="2" />
                    <path d="M22 4L12 14.01l-3-3" stroke="currentColor" stroke-width="2" />
                </svg>
            </div>
            <div class="stat-info">
                <div class="stat-label">Attended</div>
                <div class="stat-value">{{ attendedCount }}</div>
            </div>
        </div>
        <div class="stat-card purple">
            <div class="stat-icon">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
                    <path d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" stroke="currentColor" stroke-width="2" />
                </svg>
            </div>
            <div class="stat-info">
                <div class="stat-label">Registered</div>
                <div class="stat-value">{{ registeredCount }}</div>
            </div>
        </div>
        <div class="stat-card orange">
            <div class="stat-icon">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
                    <rect x="3" y="4" width="18" height="18" rx="2" stroke="currentColor" stroke-width="2" />
                </svg>
            </div>
            <div class="stat-info">
                <div class="stat-label">Events</div>
                <div class="stat-value">{{ events.length - 1 }}</div>
            </div>
        </div>
    </div>

    <!-- Filters -->
    <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-6 mb-6">
        <div class="flex flex-col gap-4">
            <div class="relative">
                <svg class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" fill="none"
                    viewBox="0 0 24 24" stroke="currentColor">
                    <path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" stroke-width="2" />
                </svg>
                <input type="text" placeholder="Search by name or email..." [value]="searchQuery"
                    (input)="onSearchChange($event)"
                    class="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500" />
            </div>
            <div class="flex gap-4">
                <select [value]="selectedEvent" (change)="onEventFilterChange($event)"
                    class="flex-1 px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500">
                    <option *ngFor="let event of events" [value]="event.id">{{ event.title }}</option>
                </select>
                <select [value]="selectedStatus" (change)="onStatusFilterChange($event)"
                    class="flex-1 px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500">
                    <option *ngFor="let status of statuses" [value]="status">
                        {{ status === 'all' ? 'All Status' : (status | titlecase) }}
                    </option>
                </select>
            </div>
        </div>
    </div>

    <!-- Participants Table -->
    <div class="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
        <div class="overflow-x-auto">
            <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                    <tr>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                            Participant</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Contact
                        </th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Event
                        </th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                            Registration</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status
                        </th>
                    </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                    <tr *ngFor="let participant of filteredParticipants" class="hover:bg-gray-50">
                        <td class="px-6 py-4 whitespace-nowrap">
                            <div class="flex items-center">
                                <div
                                    class="w-10 h-10 rounded-full bg-primary-100 flex items-center justify-center mr-4">
                                    <span class="text-primary-600 font-semibold text-sm">
                                        {{ participant.first_name.charAt(0) }}{{
                                        participant.last_name.charAt(0) }}
                                    </span>
                                </div>
                                <div class="text-sm font-medium text-gray-900">
                                    {{ participant.first_name }} {{ participant.last_name }}
                                </div>
                            </div>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap">
                            <div class="text-sm text-gray-900">{{ participant.email }}</div>
                            <div class="text-sm text-gray-500">{{ participant.phone || 'No phone' }}</div>
                        </td>
                        <td class="px-6 py-4">
                            <span class="inline-flex px-2 py-1 rounded-full text-xs bg-blue-100 text-blue-800">
                                {{ participant.event_title }}
                            </span>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                            {{ participant.registration_date | date }}
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap">
                            <span [ngClass]="getStatusColor(participant.status)"
                                class="inline-flex px-2 py-1 text-xs font-semibold rounded-full">
                                {{ participant.status }}
                            </span>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <!-- Empty State -->
    <div *ngIf="filteredParticipants.length === 0" class="text-center py-12">
        <svg class="mx-auto h-16 w-16 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path
                d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"
                stroke-width="2" />
        </svg>
        <h3 class="text-lg font-medium text-gray-900 mb-2 mt-4">No participants found</h3>
        <p class="text-gray-500">Try adjusting your search or filter criteria</p>
    </div>
</div>
