// src-react-backup/pages/EmailVerification.js
import React, { useState, useEffect, useRef, useCallback } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { Mail, CheckCircle, Loader2, RefreshCw, ArrowRight, Search } from 'lucide-react';
import { auth, supabase } from '../lib/supabase';
import { appConfig } from '../config/appConfig';
import { useToast } from '../contexts/ToastContext';

const EmailVerification = () => {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const toast = useToast();
  const [isVerifying, setIsVerifying] = useState(false);
  const [isVerified, setIsVerified] = useState(false);
  const [email, setEmail] = useState('');
  const [isResending, setIsResending] = useState(false);
  const [isCheckingStatus, setIsCheckingStatus] = useState(false);
  const [lastChecked, setLastChecked] = useState(null);
  const pollingIntervalRef = useRef(null);
  const userIdRef = useRef(null);
  const broadcastChannelRef = useRef(null);

  // Stop polling (defined early so it's available to effects)
  const stopPolling = useCallback(() => {
    if (pollingIntervalRef.current) {
      clearInterval(pollingIntervalRef.current);
      pollingIntervalRef.current = null;
    }
  }, []);

  // Set up cross-tab communication for verification status
  useEffect(() => {
    // Create a BroadcastChannel for cross-tab communication
    if (typeof BroadcastChannel !== 'undefined') {
      broadcastChannelRef.current = new BroadcastChannel('email-verification');
      
      // Listen for verification messages from other tabs
      broadcastChannelRef.current.onmessage = (event) => {
        if (event.data.type === 'email-verified') {
          // Another tab verified the email, update this tab
          setIsVerified(true);
          stopPolling();
          toast.success('Email verified in another tab! Redirecting to login...');
          setTimeout(() => {
            navigate('/login?verified=success');
          }, 1500);
        }
      };
    }

    // Also listen to localStorage changes (fallback for browsers without BroadcastChannel)
    const handleStorageChange = (e) => {
      if (e.key === 'email-verified' && e.newValue === 'true') {
        setIsVerified(true);
        stopPolling();
        toast.success('Email verified! Redirecting to login...');
        setTimeout(() => {
          navigate('/login?verified=success');
        }, 1500);
      }
    };
    window.addEventListener('storage', handleStorageChange);

    return () => {
      if (broadcastChannelRef.current) {
        broadcastChannelRef.current.close();
      }
      window.removeEventListener('storage', handleStorageChange);
    };
  }, [navigate, toast, stopPolling]);

  // Check if this is a callback from email verification link
  useEffect(() => {
    const checkVerification = async () => {
      try {
        // Supabase email verification uses hash fragments (#) in the URL
        // Check for hash fragments first (from email link)
        const hashParams = new URLSearchParams(window.location.hash.substring(1));
        const accessToken = hashParams.get('access_token');
        const type = hashParams.get('type');
        
        // Also check query params (fallback)
        const token = searchParams.get('token') || hashParams.get('token');
        const queryType = searchParams.get('type') || type;
        
        if ((accessToken || token) && (queryType === 'signup' || type === 'signup')) {
          setIsVerifying(true);
          
          // Supabase automatically handles the session when user clicks email link
          // Just check if user is now authenticated and email is confirmed
          const { data: { session }, error: sessionError } = await supabase.auth.getSession();
          
          if (sessionError) {
            console.error('Session error:', sessionError);
            toast.error('Verification failed. Please try again or request a new verification email.');
            setIsVerifying(false);
            return;
          }

          if (session?.user?.email_confirmed_at) {
            // Success! Email is verified
            setIsVerified(true);
            setIsVerifying(false);
            
            // Broadcast to other tabs that verification is complete
            if (broadcastChannelRef.current) {
              broadcastChannelRef.current.postMessage({ type: 'email-verified' });
            }
            // Also use localStorage as fallback
            localStorage.setItem('email-verified', 'true');
            setTimeout(() => localStorage.removeItem('email-verified'), 5000);
            
            // Sign out the user (they'll need to log in)
            await auth.signOut();
            
            // Show message to close this tab if it was opened from email
            const isFromEmail = window.opener === null && window.history.length <= 2;
            
            // Redirect to login with success message after a short delay
            setTimeout(() => {
              navigate('/login?verified=success');
              // If opened from email, suggest closing this tab
              if (isFromEmail) {
                setTimeout(() => {
                  if (window.opener) {
                    // If there's an opener window, close this tab
                    window.close();
                  }
                }, 3000);
              }
            }, 2000);
          } else {
            // Token present but not verified yet, wait a bit and check again
            setTimeout(async () => {
              const { data: { session: newSession } } = await supabase.auth.getSession();
              if (newSession?.user?.email_confirmed_at) {
                setIsVerified(true);
                setIsVerifying(false);
                
                // Broadcast to other tabs
                if (broadcastChannelRef.current) {
                  broadcastChannelRef.current.postMessage({ type: 'email-verified' });
                }
                localStorage.setItem('email-verified', 'true');
                setTimeout(() => localStorage.removeItem('email-verified'), 5000);
                
                await auth.signOut();
                setTimeout(() => {
                  navigate('/login?verified=success');
                }, 2000);
              } else {
                toast.error('Verification failed. Please try again or request a new verification email.');
                setIsVerifying(false);
              }
            }, 1000);
          }
        } else {
          // No token, just show the waiting page
          // Try to get email from URL or session
          const emailParam = searchParams.get('email') || hashParams.get('email');
          if (emailParam) {
            setEmail(emailParam);
          } else {
            // Try to get from current session
            const { user } = await auth.getCurrentUser();
            if (user) {
              setEmail(user.email);
              // If user is already verified, redirect to login
              if (user.email_confirmed_at) {
                navigate('/login?verified=success');
              }
            }
          }
        }
      } catch (error) {
        console.error('Error checking verification:', error);
        setIsVerifying(false);
      }
    };

    checkVerification();
  }, [searchParams, navigate, toast]);

  // Function to check verification status
  const checkVerificationStatus = useCallback(async (showToast = true) => {
    if (!email) return false;
    
    setIsCheckingStatus(true);
    try {
      // Try to sign in with a refresh to check if email is now confirmed
      const { data: { session }, error } = await supabase.auth.getSession();
      
      if (session?.user?.email_confirmed_at) {
        // User is verified!
        setIsVerified(true);
        stopPolling();
        
        // Broadcast to other tabs
        if (broadcastChannelRef.current) {
          broadcastChannelRef.current.postMessage({ type: 'email-verified' });
        }
        localStorage.setItem('email-verified', 'true');
        setTimeout(() => localStorage.removeItem('email-verified'), 5000);
        
        // Sign out and redirect to login
        await auth.signOut();
        if (showToast) {
          toast.success('Email verified! Redirecting to login...');
        }
        setTimeout(() => {
          navigate('/login?verified=success');
        }, 1500);
        return true;
      }
      
      // Also try to refresh the session to get latest status
      const { data: refreshData } = await supabase.auth.refreshSession();
      if (refreshData?.session?.user?.email_confirmed_at) {
        setIsVerified(true);
        stopPolling();
        
        // Broadcast to other tabs
        if (broadcastChannelRef.current) {
          broadcastChannelRef.current.postMessage({ type: 'email-verified' });
        }
        localStorage.setItem('email-verified', 'true');
        setTimeout(() => localStorage.removeItem('email-verified'), 5000);
        
        await auth.signOut();
        if (showToast) {
          toast.success('Email verified! Redirecting to login...');
        }
        setTimeout(() => {
          navigate('/login?verified=success');
        }, 1500);
        return true;
      }

      setLastChecked(new Date());
      if (showToast) {
        toast.info('Email not yet verified. Please check your inbox and click the verification link.');
      }
      return false;
    } catch (error) {
      console.error('Error checking verification status:', error);
      if (showToast) {
        toast.error('Unable to check verification status. Please try again.');
      }
      return false;
    } finally {
      setIsCheckingStatus(false);
    }
  }, [email, navigate, toast]);

  // Start polling for verification status
  const startPolling = useCallback(() => {
    if (pollingIntervalRef.current) return; // Already polling
    
    pollingIntervalRef.current = setInterval(() => {
      checkVerificationStatus(false); // Don't show toast for automatic checks
    }, 5000); // Check every 5 seconds
  }, [checkVerificationStatus]);

  // Cleanup polling on unmount
  useEffect(() => {
    return () => {
      stopPolling();
    };
  }, [stopPolling]);

  // Start polling when email is available and not verified
  useEffect(() => {
    if (email && !isVerified && !isVerifying) {
      startPolling();
    }
    return () => {
      stopPolling();
    };
  }, [email, isVerified, isVerifying, startPolling, stopPolling]);

  const handleResendEmail = async () => {
    if (!email) {
      toast.error('Email address not found. Please sign up again.');
      return;
    }

    setIsResending(true);
    try {
      const { error } = await supabase.auth.resend({
        type: 'signup',
        email: email
      });

      if (error) {
        toast.error(`Unable to resend verification email: ${error.message}`);
      } else {
        toast.success('Verification email has been resent. Please check your inbox.');
      }
    } catch (error) {
      toast.error('Unable to resend verification email. Please try again later.');
    } finally {
      setIsResending(false);
    }
  };

  // Manual check status handler
  const handleCheckStatus = () => {
    checkVerificationStatus(true);
  };

  if (isVerifying) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center px-3 sm:px-4">
        <div className="max-w-md w-full bg-white rounded-xl sm:rounded-2xl shadow-xl p-5 sm:p-8 text-center">
          <Loader2 className="h-12 w-12 sm:h-16 sm:w-16 animate-spin text-primary-600 mx-auto mb-3 sm:mb-4" />
          <h2 className="text-xl sm:text-2xl font-bold text-gray-900 mb-2">Verifying Your Email</h2>
          <p className="text-sm sm:text-base text-gray-600">Please wait while we verify your email address...</p>
        </div>
      </div>
    );
  }

  if (isVerified) {
    const isFromEmail = window.opener === null && window.history.length <= 2;
    
    return (
      <div className="min-h-screen bg-gradient-to-br from-green-50 to-emerald-100 flex items-center justify-center px-3 sm:px-4">
        <div className="max-w-md w-full bg-white rounded-xl sm:rounded-2xl shadow-xl p-5 sm:p-8 text-center">
          <div className="mb-4 sm:mb-6">
            <div className="h-12 w-12 sm:h-16 sm:w-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-3 sm:mb-4">
              <CheckCircle className="h-8 w-8 sm:h-10 sm:w-10 text-green-600" />
            </div>
            <h2 className="text-xl sm:text-2xl font-bold text-gray-900 mb-2">Email Verified!</h2>
            <p className="text-sm sm:text-base text-gray-600 mb-4">
              Your email has been successfully verified. Redirecting to login...
            </p>
            {isFromEmail && (
              <p className="text-xs sm:text-sm text-gray-500 italic">
                You can close this tab and return to the original page.
              </p>
            )}
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center px-3 sm:px-4 py-6 sm:py-0">
      <div className="max-w-md w-full bg-white rounded-xl sm:rounded-2xl shadow-xl p-5 sm:p-8">
        {/* Header */}
        <div className="text-center mb-5 sm:mb-8">
          <div className="h-12 w-12 sm:h-16 sm:w-16 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-3 sm:mb-4">
            <Mail className="h-7 w-7 sm:h-10 sm:w-10 text-blue-600" />
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-1.5 sm:mb-2">Verify Your Email</h1>
          <p className="text-sm sm:text-base text-gray-600">
            We've sent a verification email to <span className="font-semibold text-gray-900 break-all">{email || 'your email address'}</span>
          </p>
        </div>

        {/* Instructions */}
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 sm:p-6 mb-4 sm:mb-6">
          <h3 className="font-semibold text-gray-900 text-sm sm:text-base mb-2 sm:mb-3">Next Steps:</h3>
          <ol className="space-y-1.5 sm:space-y-2 text-xs sm:text-sm text-gray-700">
            <li className="flex items-start">
              <span className="font-bold text-blue-600 mr-2">1.</span>
              <span>Check your email inbox (and spam folder)</span>
            </li>
            <li className="flex items-start">
              <span className="font-bold text-blue-600 mr-2">2.</span>
              <span>Click the verification link in the email</span>
            </li>
            <li className="flex items-start">
              <span className="font-bold text-blue-600 mr-2">3.</span>
              <span>You'll be redirected to login once verified</span>
            </li>
          </ol>
        </div>

        {/* Auto-checking indicator */}
        <div className="bg-green-50 border border-green-200 rounded-lg p-3 sm:p-4 mb-4 sm:mb-6">
          <div className="flex items-center">
            <div className="relative mr-2 sm:mr-3 flex-shrink-0">
              <div className="w-2.5 h-2.5 sm:w-3 sm:h-3 bg-green-500 rounded-full animate-pulse"></div>
            </div>
            <div className="min-w-0">
              <p className="text-xs sm:text-sm font-medium text-green-800">Auto-checking verification status</p>
              <p className="text-xs text-green-600 truncate">
                {lastChecked 
                  ? `Last checked: ${lastChecked.toLocaleTimeString()}`
                  : 'Checking every 5 seconds...'}
              </p>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="space-y-2.5 sm:space-y-3">
          {/* Check Status Button */}
          <button
            onClick={handleCheckStatus}
            disabled={isCheckingStatus}
            className="w-full flex items-center justify-center px-4 py-2.5 sm:py-3 bg-primary-600 text-white text-sm sm:text-base rounded-lg hover:bg-primary-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed font-medium"
          >
            {isCheckingStatus ? (
              <>
                <Loader2 className="h-4 w-4 sm:h-5 sm:w-5 animate-spin mr-2" />
                Checking...
              </>
            ) : (
              <>
                <Search className="h-4 w-4 sm:h-5 sm:w-5 mr-2" />
                Check Verification Status
              </>
            )}
          </button>

          {/* Resend Email Button */}
          <button
            onClick={handleResendEmail}
            disabled={isResending || !email}
            className="w-full flex items-center justify-center px-4 py-2.5 sm:py-3 bg-white text-sm sm:text-base border-2 border-gray-300 rounded-lg hover:border-primary-500 hover:text-primary-600 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isResending ? (
              <>
                <Loader2 className="h-4 w-4 sm:h-5 sm:w-5 animate-spin mr-2" />
                Sending...
              </>
            ) : (
              <>
                <RefreshCw className="h-4 w-4 sm:h-5 sm:w-5 mr-2" />
                Resend Verification Email
              </>
            )}
          </button>

          <Link
            to="/login"
            className="block w-full text-center px-4 py-2.5 sm:py-3 text-sm sm:text-base text-gray-600 hover:text-gray-900 transition-colors"
          >
            Back to Login
          </Link>
        </div>

        {/* Help Text */}
        <div className="mt-4 sm:mt-6 pt-4 sm:pt-6 border-t border-gray-200">
          <p className="text-xs text-gray-500 text-center leading-relaxed">
            Didn't receive the email? Check your spam folder or try resending.
            Already verified? Click "Check Verification Status" above.
            If you continue to have issues, please contact support.
          </p>
        </div>
      </div>
    </div>
  );
};

export default EmailVerification;

// src/app/features/auth/pages/email-verification/email-verification.component.ts
import { Component, OnInit, OnDestroy, NgZone } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router, ActivatedRoute } from '@angular/router';
import { AuthService } from '../../../../core/services/auth.service';
import { SupabaseService } from '../../../../core/services/supabase.service';

@Component({
    selector: 'app-email-verification',
    standalone: true,
    imports: [CommonModule, RouterModule],
    templateUrl: './email-verification.component.html',
    styles: []
})
export class EmailVerificationComponent implements OnInit, OnDestroy {
    isVerifying = false;
    isVerified = false;
    email = '';
    isResending = false;
    isCheckingStatus = false;
    lastChecked: Date | null = null;
    errorMessage = ''; // Added for error display

    private pollingInterval: any;

    constructor(
        private authService: AuthService,
        private supabaseService: SupabaseService,
        private router: Router,
        private route: ActivatedRoute,
        private ngZone: NgZone
    ) { }

    async ngOnInit() {
        // Get email from query params if available
        this.route.queryParams.subscribe(params => {
            if (params['email']) {
                this.email = params['email'];
            }
        });

        // Check for verification tokens in URL (Supabase flow)
        // Actually Supabase handles this automatically on initial load if we use their client correctly
        // But we might need to capture state from the URL hash.

        // Check if user is already logged in
        const { user } = await this.supabaseService.getCurrentUser();
        if (user) {
            if (this.email === '') {
                this.email = user.email || '';
            }

            if (user.email_confirmed_at) {
                this.isVerified = true;
            } else {
                // Not verified yet, start polling
                this.startPolling();
            }
        } else {
            // If not logged in, maybe we just came from signup?
            // We can't really poll if we don't have a session, unless we rely on the user clicking the link
        }
    }

    ngOnDestroy() {
        this.stopPolling();
    }

    startPolling() {
        if (this.pollingInterval) return;
        this.pollingInterval = setInterval(() => {
            this.checkVerificationStatus(false);
        }, 5000);
    }

    stopPolling() {
        if (this.pollingInterval) {
            clearInterval(this.pollingInterval);
            this.pollingInterval = null;
        }
    }

    async checkVerificationStatus(manual: boolean = true) {
        if (!this.email) return; // Can't check without context

        if (manual) this.isCheckingStatus = true;

        try {
            // Refresh session to see if status updated
            const { data } = await this.supabaseService.client.auth.refreshSession();

            if (data.session?.user?.email_confirmed_at) {
                this.isVerified = true;
                this.stopPolling();
                // Redirect to login after success
                setTimeout(() => {
                    this.ngZone.run(() => this.router.navigate(['/login'], { queryParams: { verified: 'success' } }));
                }, 3000);
            } else {
                this.lastChecked = new Date();
                if (manual) {
                    // Show toast or message?
                    // For now just update last checked
                }
            }
        } catch (e) {
            console.error('Error checking status', e);
        } finally {
            if (manual) this.isCheckingStatus = false;
        }
    }

    async handleResendEmail() {
        if (!this.email) return;

        this.isResending = true;
        try {
            const { error } = await this.supabaseService.client.auth.resend({
                type: 'signup',
                email: this.email
            });

            if (error) {
                this.errorMessage = error.message;
            } else {
                // Success toast?
                alert('Verification email sent!');
            }
        } catch (e: any) {
            this.errorMessage = e.message || 'Failed to resend email';
        } finally {
            this.isResending = false;
        }
    }
}

<div class="min-h-screen bg-white relative overflow-hidden w-full">
    <!-- Navigation Bar -->
    <nav class="bg-white border-b border-gray-200 sticky top-0 z-50 relative">
        <div class="max-w-7xl mx-auto px-3 sm:px-6 lg:px-8">
            <div class="flex justify-between items-center h-14 sm:h-16">
                <a routerLink="/" class="flex items-center">
                    <svg class="h-6 w-6 sm:h-8 sm:w-8 text-primary-600 mr-1.5 sm:mr-2" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
                        <line x1="16" y1="2" x2="16" y2="6"></line>
                        <line x1="8" y1="2" x2="8" y2="6"></line>
                        <line x1="3" y1="10" x2="21" y2="10"></line>
                    </svg>
                    <span class="text-lg sm:text-2xl font-bold text-gray-900">EventEase</span>
                </a>
                <div class="flex items-center space-x-2 sm:space-x-4">
                    <a routerLink="/login"
                        class="text-gray-700 hover:text-primary-600 px-2 sm:px-4 py-1.5 sm:py-2 text-sm sm:text-base font-medium transition-colors">
                        Sign In
                    </a>
                    <a routerLink="/signup"
                        class="bg-primary-600 text-white px-3 sm:px-6 py-1.5 sm:py-2 text-sm sm:text-base rounded-lg hover:bg-primary-700 font-medium transition-colors">
                        Get Started
                    </a>
                </div>
            </div>
        </div>
    </nav>

    <!-- Subtle background logo -->
    <div class="absolute inset-0 flex items-center justify-center pointer-events-none overflow-hidden">
        <div
            class="text-[#3B82F6] opacity-5 text-[6rem] sm:text-[12rem] md:text-[16rem] lg:text-[20rem] font-black tracking-wider select-none whitespace-nowrap">
            EVENTEASE
        </div>
    </div>

    <!-- Main content -->
    <div class="relative z-10 font-sans min-h-[calc(100vh-64px)] flex flex-col">
        <!-- Verification Section -->
        <div class="flex-1 flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
            <div class="max-w-md w-full bg-white rounded-xl shadow-2xl border border-gray-100 p-8 text-center">

                <!-- Verifying State -->
                <div *ngIf="isVerifying">
                    <div class="flex justify-center mb-4">
                        <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600"></div>
                    </div>
                    <h2 class="text-2xl font-bold text-gray-900 mb-2">Verifying Your Email</h2>
                    <p class="text-gray-600">Please wait while we verify your email address...</p>
                </div>

                <!-- Verified State -->
                <div *ngIf="isVerified">
                    <div class="flex justify-center mb-4">
                        <div class="h-16 w-16 bg-green-100 rounded-full flex items-center justify-center">
                            <svg class="h-10 w-10 text-green-600" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path>
                                <polyline points="22 4 12 14.01 9 11.01"></polyline>
                            </svg>
                        </div>
                    </div>
                    <h2 class="text-2xl font-bold text-gray-900 mb-2">Email Verified!</h2>
                    <p class="text-gray-600 mb-6">
                        Your email has been successfully verified. Redirecting to login...
                    </p>
                </div>

                <!-- Unverified / Waiting State -->
                <div *ngIf="!isVerified && !isVerifying">
                    <div class="flex justify-center mb-6">
                        <div class="h-16 w-16 bg-blue-100 rounded-full flex items-center justify-center">
                            <svg class="h-10 w-10 text-blue-600" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z">
                                </path>
                                <polyline points="22,6 12,13 2,6"></polyline>
                            </svg>
                        </div>
                    </div>

                    <h1 class="text-2xl font-bold text-gray-900 mb-2">Verify Your Email</h1>
                    <p class="text-gray-600 mb-1">
                        We've sent a verification email to
                    </p>
                    <p class="text-gray-900 font-semibold mb-6 break-all">
                        {{ email || 'your email address' }}
                    </p>

                    <!-- Instructions -->
                    <div class="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-6 text-left">
                        <h3 class="font-semibold text-gray-900 text-sm mb-2">Next Steps:</h3>
                        <ol class="space-y-2 text-sm text-gray-700">
                            <li class="flex items-start">
                                <span class="font-bold text-blue-600 mr-2">1.</span>
                                <span>Check your email inbox (and spam folder)</span>
                            </li>
                            <li class="flex items-start">
                                <span class="font-bold text-blue-600 mr-2">2.</span>
                                <span>Click the verification link in the email</span>
                            </li>
                            <li class="flex items-start">
                                <span class="font-bold text-blue-600 mr-2">3.</span>
                                <span>You'll be redirected to login once verified</span>
                            </li>
                        </ol>
                    </div>

                    <!-- Actions -->
                    <div class="space-y-3">
                        <button (click)="checkVerificationStatus(true)" [disabled]="isCheckingStatus"
                            class="w-full flex items-center justify-center px-4 py-3 bg-primary-600 text-white font-medium rounded-lg hover:bg-primary-700 transition-colors disabled:opacity-50">
                            <span *ngIf="isCheckingStatus" class="mr-2">
                                <div class="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                            </span>
                            Check Verification Status
                        </button>

                        <button (click)="handleResendEmail()" [disabled]="isResending || !email"
                            class="w-full flex items-center justify-center px-4 py-3 bg-white text-gray-700 font-medium border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors disabled:opacity-50">
                            <svg class="h-4 w-4 mr-2" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                <polyline points="23 4 23 10 17 10"></polyline>
                                <polyline points="1 20 1 14 7 14"></polyline>
                                <path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"></path>
                            </svg>
                            Resend Verification Email
                        </button>
                    </div>

                    <div *ngIf="lastChecked" class="mt-4 text-xs text-gray-500">
                        Last checked: {{ lastChecked | date:'mediumTime' }}
                    </div>

                    <div *ngIf="errorMessage" class="mt-4 text-sm text-red-600">
                        {{ errorMessage }}
                    </div>

                    <div class="mt-6 pt-6 border-t border-gray-200">
                        <a routerLink="/login" class="text-sm text-gray-600 hover:text-gray-900 font-medium">
                            Back to Login
                        </a>
                    </div>
                </div>

            </div>
        </div>

        <!-- Footer -->
        <footer class="bg-gray-50 border-t border-gray-200 py-4">
            <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div class="text-center">
                    <p class="text-sm text-gray-600">
                        © 2025 EventEase. All rights reserved. | Your ultimate event management solution.
                    </p>
                </div>
            </div>
        </footer>
    </div>
</div>
