// src/app/features/events/components/event-qrcode-generator/event-qrcode-generator.component.ts
import { Component, EventEmitter, Input, OnChanges, Output, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { QRCodeService } from '../../../../core/services/qrcode.service';

@Component({
    selector: 'app-event-qrcode-generator',
    standalone: true,
    imports: [CommonModule, FormsModule],
    templateUrl: './event-qrcode-generator.component.html',
    styles: []
})
export class EventQRCodeGeneratorComponent implements OnChanges {
    @Input() eventId: string | undefined;
    @Input() eventTitle: string | undefined;
    @Output() close = new EventEmitter<void>();

    qrCodeData: any = null;
    loading: boolean = true;
    error: string | null = null;
    copied: boolean = false;
    customMessage: string = '';

    constructor(private qrCodeService: QRCodeService) { }

    ngOnChanges(changes: SimpleChanges): void {
        if ((changes['eventId'] || changes['eventTitle']) && this.eventId && this.eventTitle) {
            this.generateEventQRCode();
        }
    }

    async generateEventQRCode() {
        if (!this.eventId || !this.eventTitle) return;

        try {
            this.loading = true;
            this.error = null;

            const qrData = await this.qrCodeService.generateEventCheckInQRCode(
                this.eventId,
                this.eventTitle
            );

            this.qrCodeData = qrData;
        } catch (error) {
            console.error('Error generating event QR code:', error);
            this.error = 'Failed to generate QR code';
        } finally {
            this.loading = false;
        }
    }

    async generateCustomQRCode() {
        if (!this.customMessage.trim()) {
            this.error = 'Please enter a custom message';
            return;
        }

        if (!this.eventId || !this.eventTitle) return;

        try {
            this.loading = true;
            this.error = null;

            const customData = {
                eventId: this.eventId,
                eventTitle: this.eventTitle,
                customMessage: this.customMessage,
                type: 'custom_event_message',
                timestamp: new Date().toISOString()
            };

            const qrData = await this.qrCodeService.generateStyledQRCode(customData);

            this.qrCodeData = {
                dataURL: qrData,
                data: JSON.stringify(customData),
                eventData: customData
            };
        } catch (error) {
            console.error('Error generating custom QR code:', error);
            this.error = 'Failed to generate custom QR code';
        } finally {
            this.loading = false;
        }
    }

    handleDownload() {
        if (this.qrCodeData) {
            const safeTitle = this.eventTitle?.replace(/[^a-zA-Z0-9]/g, '-') || 'event';
            this.qrCodeService.downloadQRCode(
                this.qrCodeData.dataURL,
                `eventease-event-qr-${safeTitle}.png`
            );
        }
    }

    async handleCopyData() {
        if (this.qrCodeData) {
            try {
                await navigator.clipboard.writeText(this.qrCodeData.data);
                this.copied = true;
                setTimeout(() => this.copied = false, 2000);
            } catch (error) {
                console.error('Error copying QR data:', error);
            }
        }
    }

    handleRefresh() {
        this.generateEventQRCode();
    }

    onClose(event?: Event) {
        if (event) {
            event.stopPropagation();
        }
        this.close.emit();
    }
}

<div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-[100] p-3 sm:p-4"
    (click)="onClose($event)">
    <div *ngIf="loading"
        class="bg-white rounded-lg shadow-xl w-full max-w-[calc(100vw-24px)] sm:max-w-md p-4 sm:p-6 relative"
        (click)="$event.stopPropagation()">
        <div class="flex items-center justify-center py-8 sm:py-12">
            <svg class="animate-spin text-primary-600 mr-3 h-6 w-6" viewBox="0 0 24 24" fill="none"
                stroke="currentColor">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                <path class="opacity-75" fill="currentColor"
                    d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z">
                </path>
            </svg>
            <span class="text-sm sm:text-base text-gray-600">Generating QR code...</span>
        </div>
    </div>

    <div *ngIf="!loading"
        class="bg-white rounded-lg shadow-xl w-full max-w-[calc(100vw-24px)] sm:max-w-lg max-h-[90vh] overflow-y-auto relative"
        (click)="$event.stopPropagation()">
        <div class="p-4 sm:p-6">
            <!-- Header -->
            <div class="flex items-center justify-between mb-4 sm:mb-6">
                <div class="flex items-center min-w-0">
                    <!-- QrCode Icon -->
                    <svg class="text-primary-600 mr-2 sm:mr-3 flex-shrink-0 w-5 h-5" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2">
                        <rect x="3" y="3" width="7" height="7"></rect>
                        <rect x="14" y="3" width="7" height="7"></rect>
                        <rect x="14" y="14" width="7" height="7"></rect>
                        <rect x="3" y="14" width="7" height="7"></rect>
                    </svg>
                    <h3 class="text-base sm:text-lg font-semibold text-gray-900 truncate">Event QR Code</h3>
                </div>
                <button (click)="onClose()" class="text-gray-400 hover:text-gray-600 p-1 flex-shrink-0">
                    ✕
                </button>
            </div>

            <!-- Event Info -->
            <div class="bg-blue-50 border border-blue-200 rounded-lg p-3 sm:p-4 mb-4 sm:mb-6">
                <div class="flex items-start sm:items-center">
                    <!-- Calendar Icon -->
                    <svg class="text-blue-600 mr-2 sm:mr-3 flex-shrink-0 mt-0.5 sm:mt-0 w-[18px] h-[18px]"
                        viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
                        <line x1="16" y1="2" x2="16" y2="6"></line>
                        <line x1="8" y1="2" x2="8" y2="6"></line>
                        <line x1="3" y1="10" x2="21" y2="10"></line>
                    </svg>
                    <div class="min-w-0">
                        <h4 class="font-medium text-blue-900 text-sm sm:text-base break-words">{{ eventTitle }}</h4>
                        <p class="text-xs sm:text-sm text-blue-800 truncate">Event ID: {{ eventId }}</p>
                    </div>
                </div>
            </div>

            <!-- QR Code Display -->
            <div *ngIf="qrCodeData && !error" class="text-center mb-4 sm:mb-6">
                <div class="bg-white p-3 sm:p-6 rounded-lg border-2 border-gray-200 inline-block mb-3 sm:mb-4">
                    <img [src]="qrCodeData.dataURL" alt="Event QR Code" class="w-36 h-36 sm:w-48 sm:h-48 mx-auto" />
                </div>

                <div class="space-y-2 sm:space-y-3">
                    <div class="flex flex-col gap-2 sm:gap-3">
                        <button (click)="handleDownload()"
                            class="btn-primary flex items-center justify-center text-sm sm:text-base py-2.5 sm:py-2">
                            <!-- Download Icon -->
                            <svg class="mr-2 w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                stroke-width="2">
                                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
                                <polyline points="7 10 12 15 17 10"></polyline>
                                <line x1="12" y1="15" x2="12" y2="3"></line>
                            </svg>
                            Download QR Code
                        </button>
                        <button (click)="handleCopyData()"
                            class="btn-secondary flex items-center justify-center text-sm sm:text-base py-2.5 sm:py-2">
                            <ng-container *ngIf="copied; else copyIcon">
                                <!-- Check Icon -->
                                <svg class="mr-2 w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                    stroke-width="2">
                                    <polyline points="20 6 9 17 4 12"></polyline>
                                </svg>
                                Copied!
                            </ng-container>
                            <ng-template #copyIcon>
                                <!-- Copy Icon -->
                                <svg class="mr-2 w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                    stroke-width="2">
                                    <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                                    <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
                                </svg>
                                Copy Data
                            </ng-template>
                        </button>
                    </div>

                    <button (click)="handleRefresh()"
                        class="btn-secondary text-xs sm:text-sm py-2 flex items-center justify-center mx-auto">
                        <!-- Refresh Icon -->
                        <svg class="mr-2 w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                            stroke-width="2">
                            <polyline points="23 4 23 10 17 10"></polyline>
                            <polyline points="1 20 1 14 7 14"></polyline>
                            <path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"></path>
                        </svg>
                        Generate New QR Code
                    </button>
                </div>
            </div>

            <!-- Custom Message QR Code -->
            <div class="border-t pt-4 sm:pt-6">
                <h4 class="font-medium text-gray-900 mb-3 sm:mb-4 text-sm sm:text-base">Custom Message QR Code</h4>
                <div class="space-y-3 sm:space-y-4">
                    <div>
                        <label class="block text-xs sm:text-sm font-medium text-gray-700 mb-1.5 sm:mb-2">
                            Custom Message
                        </label>
                        <textarea [(ngModel)]="customMessage" placeholder="Enter a custom message for the QR code..."
                            class="input-field h-16 sm:h-20 resize-none text-sm w-full" rows="3"></textarea>
                    </div>
                    <button (click)="generateCustomQRCode()"
                        class="btn-primary w-full text-sm sm:text-base py-2.5 sm:py-2 flex items-center justify-center">
                        <!-- Plus Icon -->
                        <svg class="mr-2 w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                            stroke-width="2">
                            <line x1="12" y1="5" x2="12" y2="19"></line>
                            <line x1="5" y1="12" x2="19" y2="12"></line>
                        </svg>
                        Generate Custom QR Code
                    </button>
                </div>
            </div>

            <!-- Error State -->
            <div *ngIf="error" class="bg-red-50 border border-red-200 rounded-lg p-3 sm:p-4 mt-4 sm:mt-6">
                <div class="flex items-start">
                    <div class="flex-shrink-0">
                        <!-- QrCode Error Icon (reusing QrCode but red) -->
                        <svg class="text-red-600 w-[18px] h-[18px]" viewBox="0 0 24 24" fill="none"
                            stroke="currentColor" stroke-width="2">
                            <rect x="3" y="3" width="7" height="7"></rect>
                            <rect x="14" y="3" width="7" height="7"></rect>
                            <rect x="14" y="14" width="7" height="7"></rect>
                            <rect x="3" y="14" width="7" height="7"></rect>
                        </svg>
                    </div>
                    <div class="ml-2 sm:ml-3">
                        <p class="text-red-800 font-medium text-sm sm:text-base">Error Generating QR Code</p>
                        <p class="text-red-700 text-xs sm:text-sm mt-1">{{ error }}</p>
                        <button (click)="handleRefresh()"
                            class="mt-2 text-red-600 hover:text-red-800 underline text-xs sm:text-sm">
                            Try again
                        </button>
                    </div>
                </div>
            </div>

            <!-- Usage Instructions -->
            <div class="mt-4 sm:mt-6 p-3 sm:p-4 bg-gray-50 rounded-lg">
                <h5 class="font-medium text-gray-900 mb-2 text-sm sm:text-base">How to Use</h5>
                <div class="text-xs sm:text-sm text-gray-600 space-y-1">
                    <p>• <strong>Check-in:</strong> Scan to check into your event</p>
                    <p>• <strong>Share:</strong> Quick event info for attendees</p>
                    <p>• <strong>Custom:</strong> Special instructions or announcements</p>
                    <p>• <strong>Print:</strong> Download for physical materials</p>
                </div>
            </div>
        </div>
    </div>
</div>

// src-react-backup/components/EventQRCodeGenerator.js
import React, { useState, useEffect } from 'react';
import { 
  QrCode, 
  Download, 
  RefreshCw, 
  Calendar,
  Loader2,
  Copy,
  Check,
  Plus,
  Trash2
} from 'lucide-react';
import { qrCodeService } from '../services/qrCodeService';

const EventQRCodeGenerator = ({ eventId, eventTitle, onClose }) => {
  const [qrCodeData, setQrCodeData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [copied, setCopied] = useState(false);
  const [customMessage, setCustomMessage] = useState('');

  useEffect(() => {
    if (eventId && eventTitle) {
      generateEventQRCode();
    }
  }, [eventId, eventTitle]);

  const generateEventQRCode = async () => {
    try {
      setLoading(true);
      setError(null);

      const qrData = await qrCodeService.generateEventCheckInQRCode(
        eventId,
        eventTitle
      );

      setQrCodeData(qrData);
    } catch (error) {
      console.error('Error generating event QR code:', error);
      setError('Failed to generate QR code');
    } finally {
      setLoading(false);
    }
  };

  const generateCustomQRCode = async () => {
    if (!customMessage.trim()) {
      setError('Please enter a custom message');
      return;
    }

    try {
      setLoading(true);
      setError(null);

      const customData = {
        eventId: eventId,
        eventTitle: eventTitle,
        customMessage: customMessage,
        type: 'custom_event_message',
        timestamp: new Date().toISOString()
      };

      const qrData = await qrCodeService.generateStyledQRCode(customData);
      
      setQrCodeData({
        dataURL: qrData,
        data: JSON.stringify(customData),
        eventData: customData
      });
    } catch (error) {
      console.error('Error generating custom QR code:', error);
      setError('Failed to generate custom QR code');
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = () => {
    if (qrCodeData) {
      qrCodeService.downloadQRCode(
        qrCodeData.dataURL,
        `eventease-event-qr-${eventTitle?.replace(/[^a-zA-Z0-9]/g, '-') || 'event'}.png`
      );
    }
  };

  const handleCopyData = async () => {
    if (qrCodeData) {
      try {
        await navigator.clipboard.writeText(qrCodeData.data);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      } catch (error) {
        console.error('Error copying QR data:', error);
      }
    }
  };

  const handleRefresh = () => {
    generateEventQRCode();
  };

  if (loading) {
    return (
      <div 
        className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-[100] p-3 sm:p-4"
        onClick={(e) => {
          if (e.target === e.currentTarget && onClose) {
            onClose();
          }
        }}
      >
        <div 
          className="bg-white rounded-lg shadow-xl w-full max-w-[calc(100vw-24px)] sm:max-w-md p-4 sm:p-6 relative"
          onClick={(e) => e.stopPropagation()}
        >
          <div className="flex items-center justify-center py-8 sm:py-12">
            <Loader2 className="animate-spin text-primary-600 mr-3" size={24} />
            <span className="text-sm sm:text-base text-gray-600">Generating QR code...</span>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div 
      className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-[100] p-3 sm:p-4"
      onClick={(e) => {
        if (e.target === e.currentTarget && onClose) {
          onClose();
        }
      }}
    >
      <div 
        className="bg-white rounded-lg shadow-xl w-full max-w-[calc(100vw-24px)] sm:max-w-lg max-h-[90vh] overflow-y-auto relative"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="p-4 sm:p-6">
          {/* Header */}
          <div className="flex items-center justify-between mb-4 sm:mb-6">
            <div className="flex items-center min-w-0">
              <QrCode className="text-primary-600 mr-2 sm:mr-3 flex-shrink-0" size={20} />
              <h3 className="text-base sm:text-lg font-semibold text-gray-900 truncate">Event QR Code</h3>
            </div>
            <button
              onClick={onClose}
              className="text-gray-400 hover:text-gray-600 p-1 flex-shrink-0"
            >
              ✕
            </button>
          </div>

          {/* Event Info */}
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 sm:p-4 mb-4 sm:mb-6">
            <div className="flex items-start sm:items-center">
              <Calendar className="text-blue-600 mr-2 sm:mr-3 flex-shrink-0 mt-0.5 sm:mt-0" size={18} />
              <div className="min-w-0">
                <h4 className="font-medium text-blue-900 text-sm sm:text-base break-words">{eventTitle}</h4>
                <p className="text-xs sm:text-sm text-blue-800 truncate">Event ID: {eventId}</p>
              </div>
            </div>
          </div>

          {/* QR Code Display */}
          {qrCodeData && !error && (
            <div className="text-center mb-4 sm:mb-6">
              <div className="bg-white p-3 sm:p-6 rounded-lg border-2 border-gray-200 inline-block mb-3 sm:mb-4">
                <img
                  src={qrCodeData.dataURL}
                  alt="Event QR Code"
                  className="w-36 h-36 sm:w-48 sm:h-48 mx-auto"
                />
              </div>

              <div className="space-y-2 sm:space-y-3">
                <div className="flex flex-col gap-2 sm:gap-3">
                  <button
                    onClick={handleDownload}
                    className="btn-primary flex items-center justify-center text-sm sm:text-base py-2.5 sm:py-2"
                  >
                    <Download size={16} className="mr-2" />
                    Download QR Code
                  </button>
                  <button
                    onClick={handleCopyData}
                    className="btn-secondary flex items-center justify-center text-sm sm:text-base py-2.5 sm:py-2"
                  >
                    {copied ? (
                      <>
                        <Check size={16} className="mr-2" />
                        Copied!
                      </>
                    ) : (
                      <>
                        <Copy size={16} className="mr-2" />
                        Copy Data
                      </>
                    )}
                  </button>
                </div>

                <button
                  onClick={handleRefresh}
                  className="btn-secondary text-xs sm:text-sm py-2"
                >
                  <RefreshCw size={14} className="mr-2" />
                  Generate New QR Code
                </button>
              </div>
            </div>
          )}

          {/* Custom Message QR Code */}
          <div className="border-t pt-4 sm:pt-6">
            <h4 className="font-medium text-gray-900 mb-3 sm:mb-4 text-sm sm:text-base">Custom Message QR Code</h4>
            <div className="space-y-3 sm:space-y-4">
              <div>
                <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1.5 sm:mb-2">
                  Custom Message
                </label>
                <textarea
                  value={customMessage}
                  onChange={(e) => setCustomMessage(e.target.value)}
                  placeholder="Enter a custom message for the QR code..."
                  className="input-field h-16 sm:h-20 resize-none text-sm"
                  rows={3}
                />
              </div>
              <button
                onClick={generateCustomQRCode}
                className="btn-primary w-full text-sm sm:text-base py-2.5 sm:py-2"
              >
                <Plus size={16} className="mr-2" />
                Generate Custom QR Code
              </button>
            </div>
          </div>

          {/* Error State */}
          {error && (
            <div className="bg-red-50 border border-red-200 rounded-lg p-3 sm:p-4 mt-4 sm:mt-6">
              <div className="flex items-start">
                <div className="flex-shrink-0">
                  <QrCode className="text-red-600" size={18} />
                </div>
                <div className="ml-2 sm:ml-3">
                  <p className="text-red-800 font-medium text-sm sm:text-base">Error Generating QR Code</p>
                  <p className="text-red-700 text-xs sm:text-sm mt-1">{error}</p>
                  <button
                    onClick={handleRefresh}
                    className="mt-2 text-red-600 hover:text-red-800 underline text-xs sm:text-sm"
                  >
                    Try again
                  </button>
                </div>
              </div>
            </div>
          )}

          {/* Usage Instructions */}
          <div className="mt-4 sm:mt-6 p-3 sm:p-4 bg-gray-50 rounded-lg">
            <h5 className="font-medium text-gray-900 mb-2 text-sm sm:text-base">How to Use</h5>
            <div className="text-xs sm:text-sm text-gray-600 space-y-1">
              <p>• <strong>Check-in:</strong> Scan to check into your event</p>
              <p>• <strong>Share:</strong> Quick event info for attendees</p>
              <p>• <strong>Custom:</strong> Special instructions or announcements</p>
              <p>• <strong>Print:</strong> Download for physical materials</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default EventQRCodeGenerator;
