// src-react-backup/pages/ForgotPassword.js
import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Mail, ArrowLeft, CheckCircle } from 'lucide-react';
import { auth } from '../lib/supabase';

const ForgotPassword = () => {
  const navigate = useNavigate();
  const [email, setEmail] = useState('');
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);

  const validateEmail = (email) => {
    const emailRegex = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
    return emailRegex.test(email);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    // Clear previous errors
    setError('');

    // Validate email
    if (!email) {
      setError('Email is required');
      return;
    }

    if (!validateEmail(email)) {
      setError('Please enter a valid email address');
      return;
    }

    setIsLoading(true);
    
    try {
      // Use Supabase to send password reset email
      const { data, error } = await auth.resetPassword(email);
      
      if (error) {
        console.error('Password reset error:', error);
        setError(error.message || 'Failed to send reset email. Please check your Supabase email configuration.');
        return;
      }
      
      // Show success state
      setIsSuccess(true);
      
      // Redirect to login page after 3 seconds
      setTimeout(() => {
        navigate('/login');
      }, 3000);
      
    } catch (error) {
      console.error('Password reset exception:', error);
      setError(error.message || 'Failed to send reset email. Please check your Supabase email configuration.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleEmailChange = (e) => {
    setEmail(e.target.value);
    // Clear error when user starts typing
    if (error) {
      setError('');
    }
  };

  return (
    <div className="min-h-screen bg-white relative overflow-hidden w-full">
      {/* Subtle background logo */}
      <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
        <div className="text-[#3B82F6] opacity-5 text-[20rem] font-black tracking-wider select-none">
          EVENTEASE
        </div>
      </div>

      {/* Main content */}
      <div className="relative z-10 min-h-screen flex flex-col">
        {/* Forgot Password Form Section */}
        <div className="flex-1 flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
          <div className="max-w-md w-full">
            {/* Forgot Password Form Card */}
            <div className="bg-white rounded-xl shadow-2xl border border-gray-100 p-8">
              <div className="text-center mb-8">
                <h1 className="text-3xl font-bold text-gray-900 mb-2">
                  Forgot Password?
                </h1>
                <p className="text-sm text-gray-600">
                  No worries! Enter your email address and we'll send you a reset link.
                </p>
              </div>

              {/* Success Message */}
              {isSuccess && (
                <div className="bg-green-50 border border-green-200 rounded-lg p-6 text-center">
                  <div className="flex justify-center mb-4">
                    <CheckCircle className="h-12 w-12 text-green-500" />
                  </div>
                  <h3 className="text-lg font-semibold text-green-800 mb-2">
                    Reset Link Sent!
                  </h3>
                  <p className="text-green-700 mb-4">
                    We've sent a password reset link to <strong>{email}</strong>
                  </p>
                  <p className="text-sm text-green-600 mb-4">
                    Please check your email and follow the instructions to reset your password.
                  </p>
                  <div className="flex justify-center">
                    <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-green-600"></div>
                  </div>
                  <p className="text-xs text-green-600 mt-2">
                    Redirecting to login page...
                  </p>
                </div>
              )}

              {!isSuccess ? (
                <form className="space-y-6" onSubmit={handleSubmit}>
                  {/* Email Field */}
                  <div>
                    <label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-2">
                      Email Address
                    </label>
                    <div className="relative">
                      <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                        <Mail className="h-5 w-5 text-gray-400" />
                      </div>
                      <input
                        id="email"
                        name="email"
                        type="email"
                        autoComplete="email"
                        value={email}
                        onChange={handleEmailChange}
                        className={`block w-full pl-10 pr-3 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-colors ${
                          error ? 'border-red-500' : 'border-gray-300'
                        }`}
                        placeholder="Enter your email address"
                      />
                    </div>
                    {error && (
                      <p className="mt-1 text-sm text-red-600">{error}</p>
                    )}
                  </div>

                  {/* Submit Button */}
                  <div>
                    <button
                      type="submit"
                      disabled={isLoading}
                      className="w-full flex justify-center py-3 px-4 border border-transparent text-sm font-bold rounded-lg text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed transition-colors duration-200"
                    >
                      {isLoading ? (
                        <div className="flex items-center">
                          <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                          Sending reset link...
                        </div>
                      ) : (
                        'Send Reset Link'
                      )}
                    </button>
                  </div>

                  {/* Back to Login Link */}
                  <div className="text-center">
                    <Link 
                      to="/login" 
                      className="inline-flex items-center text-sm font-medium text-blue-600 hover:text-blue-500 transition-colors"
                    >
                      <ArrowLeft className="h-4 w-4 mr-1" />
                      Back to Login
                    </Link>
                  </div>
                </form>
              ) : null}
            </div>

            {/* Help Text */}
            <div className="mt-6 bg-blue-50 border border-blue-200 rounded-lg p-4">
              <h3 className="text-sm font-medium text-blue-800 mb-2">Need Help?</h3>
              <p className="text-xs text-blue-700">
                If you don't receive the email within a few minutes, check your spam folder or contact support.
              </p>
            </div>
          </div>
        </div>

        {/* Footer */}
        <footer className="bg-gray-50 border-t border-gray-200 py-4">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="text-center">
              <p className="text-sm text-gray-600">
                © 2025 EventEase. All rights reserved. | Your ultimate event management solution.
              </p>
            </div>
          </div>
        </footer>
      </div>
    </div>
  );
};

export default ForgotPassword;

// src/app/features/auth/pages/forgot-password/forgot-password.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../../../core/services/auth.service';

@Component({
    selector: 'app-forgot-password',
    standalone: true,
    imports: [CommonModule, ReactiveFormsModule, RouterModule],
    templateUrl: './forgot-password.component.html',
    styleUrls: ['./forgot-password.component.css']
})
export class ForgotPasswordComponent {
    forgotPasswordForm: FormGroup;
    isLoading = false;
    errorMessage = '';
    successMessage = '';

    constructor(
        private fb: FormBuilder,
        private authService: AuthService,
        private router: Router
    ) {
        this.forgotPasswordForm = this.fb.group({
            email: ['', [Validators.required, Validators.email]]
        });
    }

    async onSubmit() {
        if (this.forgotPasswordForm.invalid) {
            this.forgotPasswordForm.get('email')?.markAsTouched();
            return;
        }

        this.isLoading = true;
        this.errorMessage = '';
        this.successMessage = '';

        const { email } = this.forgotPasswordForm.value;
        const result = await this.authService.forgotPassword(email);

        this.isLoading = false;

        if (result.success) {
            this.successMessage = result.message || 'Password reset email sent!';
            this.forgotPasswordForm.reset();
            // Redirect to login after 3 seconds
            setTimeout(() => {
                this.router.navigate(['/login']);
            }, 3000);
        } else {
            this.errorMessage = result.error || 'Failed to send reset email. Please try again.';
        }
    }

    get email() {
        return this.forgotPasswordForm.get('email');
    }
}

<div class="min-h-screen bg-white relative overflow-hidden w-full">
    <!-- Navigation Bar -->
    <nav class="bg-white border-b border-gray-200 sticky top-0 z-50 relative">
        <div class="max-w-7xl mx-auto px-3 sm:px-6 lg:px-8">
            <div class="flex justify-between items-center h-14 sm:h-16">
                <a routerLink="/" class="flex items-center">
                    <svg class="h-6 w-6 sm:h-8 sm:w-8 text-primary-600 mr-1.5 sm:mr-2" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
                        <line x1="16" y1="2" x2="16" y2="6"></line>
                        <line x1="8" y1="2" x2="8" y2="6"></line>
                        <line x1="3" y1="10" x2="21" y2="10"></line>
                    </svg>
                    <span class="text-lg sm:text-2xl font-bold text-gray-900">EventEase</span>
                </a>
                <div class="flex items-center space-x-2 sm:space-x-4">
                    <a routerLink="/login"
                        class="text-gray-700 hover:text-primary-600 px-2 sm:px-4 py-1.5 sm:py-2 text-sm sm:text-base font-medium transition-colors">
                        Sign In
                    </a>
                    <a routerLink="/signup"
                        class="bg-primary-600 text-white px-3 sm:px-6 py-1.5 sm:py-2 text-sm sm:text-base rounded-lg hover:bg-primary-700 font-medium transition-colors">
                        Get Started
                    </a>
                </div>
            </div>
        </div>
    </nav>

    <!-- Subtle background logo -->
    <div class="absolute inset-0 flex items-center justify-center pointer-events-none overflow-hidden">
        <div
            class="text-[#3B82F6] opacity-5 text-[6rem] sm:text-[12rem] md:text-[16rem] lg:text-[20rem] font-black tracking-wider select-none whitespace-nowrap">
            EVENTEASE
        </div>
    </div>

    <!-- Main content -->
    <div class="relative z-10 font-sans min-h-[calc(100vh-64px)] flex flex-col">
        <!-- Forgot Password Form Section -->
        <div class="flex-1 flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
            <div class="max-w-md w-full">
                <!-- Forgot Password Form Card -->
                <div class="bg-white rounded-xl shadow-2xl border border-gray-100 p-8">
                    <div class="text-center mb-8">
                        <h1 class="text-3xl font-bold text-gray-900 mb-2">
                            Forgot Password?
                        </h1>
                        <p class="text-sm text-gray-600">
                            No worries! Enter your email address and we'll send you a reset link.
                        </p>
                    </div>

                    <!-- Success Message -->
                    <div *ngIf="successMessage" class="bg-green-50 border border-green-200 rounded-lg p-6 text-center">
                        <div class="flex justify-center mb-4">
                            <svg class="h-12 w-12 text-green-500" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path>
                                <polyline points="22 4 12 14.01 9 11.01"></polyline>
                            </svg>
                        </div>
                        <h3 class="text-lg font-semibold text-green-800 mb-2">
                            Reset Link Sent!
                        </h3>
                        <p class="text-green-700 mb-4">
                            We've sent a password reset link to <strong class="break-all">{{ email?.value }}</strong>
                        </p>
                        <p class="text-sm text-green-600 mb-4">
                            Please check your email and follow the instructions to reset your password.
                        </p>
                        <div class="flex justify-center">
                            <div class="animate-spin rounded-full h-6 w-6 border-b-2 border-green-600"></div>
                        </div>
                        <p class="text-xs text-green-600 mt-2">
                            Redirecting to login page...
                        </p>
                    </div>

                    <div *ngIf="!successMessage">
                        <form [formGroup]="forgotPasswordForm" (ngSubmit)="onSubmit()" class="space-y-6">
                            <!-- Email Field -->
                            <div>
                                <label for="email" class="block text-sm font-medium text-gray-700 mb-2">
                                    Email Address
                                </label>
                                <div class="relative">
                                    <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                                        <svg class="h-5 w-5 text-gray-400" viewBox="0 0 24 24" fill="none"
                                            stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                            stroke-linejoin="round">
                                            <path
                                                d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z">
                                            </path>
                                            <polyline points="22,6 12,13 2,6"></polyline>
                                        </svg>
                                    </div>
                                    <input id="email" formControlName="email" type="email" autocomplete="email"
                                        class="block w-full pl-10 pr-3 py-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-colors"
                                        [class.border-red-500]="email?.invalid && email?.touched"
                                        [class.border-gray-300]="!email?.invalid || !email?.touched"
                                        placeholder="Enter your email address" />
                                </div>
                                <div *ngIf="email?.invalid && email?.touched" class="mt-1 text-sm text-red-600">
                                    <span *ngIf="email?.errors?.['required']">Email is required</span>
                                    <span *ngIf="email?.errors?.['email']">Please enter a valid email address</span>
                                </div>
                                <div *ngIf="errorMessage" class="mt-1 text-sm text-red-600">
                                    {{ errorMessage }}
                                </div>
                            </div>

                            <!-- Submit Button -->
                            <div>
                                <button type="submit" [disabled]="isLoading"
                                    class="w-full flex justify-center py-3 px-4 border border-transparent text-sm font-bold rounded-lg text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed transition-colors duration-200">
                                    <span *ngIf="isLoading" class="flex items-center">
                                        <div class="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2">
                                        </div>
                                        Sending reset link...
                                    </span>
                                    <span *ngIf="!isLoading">Send Reset Link</span>
                                </button>
                            </div>

                            <!-- Back to Login Link -->
                            <div class="text-center">
                                <a routerLink="/login"
                                    class="inline-flex items-center text-sm font-medium text-blue-600 hover:text-blue-500 transition-colors">
                                    <svg class="h-4 w-4 mr-1" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                        stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                        <line x1="19" y1="12" x2="5" y2="12"></line>
                                        <polyline points="12 19 5 12 12 5"></polyline>
                                    </svg>
                                    Back to Login
                                </a>
                            </div>
                        </form>
                    </div>
                </div>

                <!-- Help Text -->
                <div class="mt-6 bg-blue-50 border border-blue-200 rounded-lg p-4" *ngIf="!successMessage">
                    <h3 class="text-sm font-medium text-blue-800 mb-2">Need Help?</h3>
                    <p class="text-xs text-blue-700">
                        If you don't receive the email within a few minutes, check your spam folder or contact support.
                    </p>
                </div>
            </div>
        </div>

        <!-- Footer -->
        <footer class="bg-gray-50 border-t border-gray-200 py-4">
            <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div class="text-center">
                    <p class="text-sm text-gray-600">
                        © 2025 EventEase. All rights reserved. | Your ultimate event management solution.
                    </p>
                </div>
            </div>
        </footer>
    </div>
</div>
