// src/app/features/admin/pages/admin-verification-review/admin-verification-review.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { VerificationService, Verification } from '../../../../core/services/verification.service';
import { StorageService } from '../../../../core/services/storage.service';
import { AuthService } from '../../../../core/services/auth.service';
import { ToastService } from '../../../../core/services/toast.service';
import { LucideAngularModule, Shield, CheckCircle, XCircle, Clock, FileText, Eye, Loader2, RefreshCw, Search, Filter, Download, AlertCircle } from 'lucide-angular';
import { SafeUrl } from '@angular/platform-browser';

@Component({
    selector: 'app-admin-verification-review',
    standalone: true,
    imports: [CommonModule, FormsModule, RouterModule, LucideAngularModule],
    templateUrl: './admin-verification-review.component.html',
    styleUrl: './admin-verification-review.component.css'
})
export class AdminVerificationReviewComponent implements OnInit {
    loading = true;
    isAdmin = false;
    user: any = null;

    verifications: Verification[] = [];
    filteredVerifications: Verification[] = [];

    selectedVerification: Verification | null = null;
    reviewModalOpen = false;
    reviewData = {
        action: '',
        rejectionReason: '',
        adminNotes: ''
    };

    documentUrl: string | null = null;
    loadingDocument = false;
    processing = false;

    // filters
    searchQuery = '';
    statusFilter = 'pending';

    // Icons
    readonly ShieldIcon = Shield;
    readonly CheckCircleIcon = CheckCircle;
    readonly XCircleIcon = XCircle;
    readonly ClockIcon = Clock;
    readonly FileTextIcon = FileText;
    readonly EyeIcon = Eye;
    readonly Loader2Icon = Loader2;
    readonly RefreshCwIcon = RefreshCw;
    readonly SearchIcon = Search;
    readonly FilterIcon = Filter;
    readonly DownloadIcon = Download;
    readonly AlertCircleIcon = AlertCircle;

    constructor(
        private verificationService: VerificationService,
        private storageService: StorageService,
        private authService: AuthService,
        private toast: ToastService,
        private router: Router
    ) { }

    async ngOnInit() {
        this.user = await this.authService.getCurrentUser();
        const role = this.user?.user_metadata?.role;
        this.isAdmin = role === 'admin' || role === 'Admin' || role === 'Administrator';

        if (!this.isAdmin) {
            this.loading = false;
            return;
        }

        await this.loadVerifications();
    }

    async loadVerifications() {
        try {
            this.loading = true;
            const { data, error } = await this.verificationService.getPendingVerifications({
                status: this.statusFilter === 'all' ? 'all' : this.statusFilter,
                limit: 100
            });

            if (error) throw error;
            this.verifications = data || [];
            this.applyFilters();
        } catch (error) {
            console.error('Error loading verifications:', error);
            this.verifications = [];
        } finally {
            this.loading = false;
        }
    }

    applyFilters() {
        let filtered = this.verifications;

        if (this.searchQuery) {
            const q = this.searchQuery.toLowerCase();
            filtered = filtered.filter(v => {
                const email = v.metadata?.user_email?.toLowerCase() || '';
                const name = v.metadata?.user_name?.toLowerCase() || '';
                const type = v.verification_type?.toLowerCase() || '';
                const docType = v.document_type?.toLowerCase() || '';

                return email.includes(q) || name.includes(q) || type.includes(q) || docType.includes(q);
            });
        }

        this.filteredVerifications = filtered;
    }

    onFilterChange() {
        // Re-fetch if status changes to ensure we get data from server (since fetch depends on status)
        // But search is local.
        // Actually `loadVerifications` uses `statusFilter`.
        // So if status changes, we should call loadVerifications, otherwise just applyFilters.
    }

    onStatusFilterChange() {
        this.loadVerifications();
    }

    onSearch() {
        this.applyFilters();
    }

    async handleViewVerification(verification: Verification) {
        this.selectedVerification = verification;
        this.reviewModalOpen = true;
        this.loadingDocument = true;
        this.documentUrl = null;
        this.reviewData = { action: '', rejectionReason: '', adminNotes: '' };

        try {
            const { data: url, error } = await this.storageService.getVerificationDocumentUrl(
                verification.file_path,
                3600
            );
            if (error) throw error;
            this.documentUrl = url;
        } catch (error) {
            console.error('Error loading document', error);
            this.toast.error('Unable to load document');
        } finally {
            this.loadingDocument = false;
        }
    }

    async handleReview() {
        if (!this.selectedVerification || !this.reviewData.action || !this.user) {
            this.toast.warning('Please select an action');
            return;
        }

        if (this.reviewData.action === 'reject' && !this.reviewData.rejectionReason.trim()) {
            this.toast.warning('Please provide a rejection reason');
            return;
        }

        this.processing = true;
        try {
            if (this.reviewData.action === 'approve') {
                const { error } = await this.verificationService.approveVerification(
                    this.selectedVerification.id,
                    this.user.id,
                    this.reviewData.adminNotes || null
                );
                if (error) throw error;
            } else {
                const { error } = await this.verificationService.rejectVerification(
                    this.selectedVerification.id,
                    this.user.id,
                    this.reviewData.rejectionReason,
                    this.reviewData.adminNotes || null
                );
                if (error) throw error;
            }

            await this.loadVerifications();
            this.closeModal();
            this.toast.success(`Verification ${this.reviewData.action}ed successfully`);

        } catch (error: any) {
            console.error('Error reviewing:', error);
            this.toast.error(`Failed to ${this.reviewData.action} verification`);
        } finally {
            this.processing = false;
        }
    }

    closeModal() {
        this.reviewModalOpen = false;
        this.selectedVerification = null;
        this.documentUrl = null;
    }

    getStatusColor(status: string): string {
        switch (status) {
            case 'approved': return 'bg-green-100 text-green-800';
            case 'rejected': return 'bg-red-100 text-red-800';
            case 'pending': return 'bg-yellow-100 text-yellow-800';
            case 'under_review': return 'bg-blue-100 text-blue-800';
            default: return 'bg-gray-100 text-gray-800';
        }
    }

    // Helpers for template access
    getUserEmail(v: Verification): string { return v.metadata?.user_email || 'N/A'; }
    getUserName(v: Verification): string { return v.metadata?.user_name || 'N/A'; }
}

<div *ngIf="loading" class="flex items-center justify-center min-h-screen">
    <div class="text-center">
        <lucide-icon [img]="Loader2Icon" class="h-12 w-12 animate-spin text-primary-600 mx-auto mb-4"></lucide-icon>
        <p class="text-gray-600">Loading verifications...</p>
    </div>
</div>

<div *ngIf="!loading && !isAdmin" class="flex items-center justify-center min-h-screen">
    <div class="text-center">
        <lucide-icon [img]="ShieldIcon" class="h-16 w-16 text-red-500 mx-auto mb-4"></lucide-icon>
        <h2 class="text-2xl font-bold text-gray-900 mb-2">Access Denied</h2>
        <p class="text-gray-600">You don't have permission.</p>
    </div>
</div>

<div *ngIf="!loading && isAdmin" class="min-h-screen bg-gray-50">
    <!-- Header -->
    <div class="bg-white shadow-sm border-b border-gray-200">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex flex-col sm:flex-row sm:justify-between sm:items-center py-4 sm:py-6 gap-3">
                <div class="min-w-0">
                    <h1 class="text-xl sm:text-3xl font-bold text-gray-900">Verification Review</h1>
                    <p class="text-sm sm:text-base text-gray-600 mt-1">Review user documents</p>
                </div>
                <button (click)="loadVerifications()"
                    class="flex items-center px-3 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50">
                    <lucide-icon [img]="RefreshCwIcon" class="h-4 w-4 mr-2"></lucide-icon>
                    Refresh
                </button>
            </div>
        </div>
    </div>

    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 sm:py-8">
        <!-- Filters -->
        <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-4 mb-6">
            <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Search</label>
                    <div class="relative">
                        <lucide-icon [img]="SearchIcon"
                            class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-4 w-4"></lucide-icon>
                        <input type="text" [(ngModel)]="searchQuery" (ngModelChange)="onSearch()"
                            placeholder="Search email..."
                            class="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500">
                    </div>
                </div>
                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-2">Status</label>
                    <select [(ngModel)]="statusFilter" (ngModelChange)="onStatusFilterChange()"
                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500">
                        <option value="pending">Pending</option>
                        <option value="under_review">Under Review</option>
                        <option value="all">All</option>
                    </select>
                </div>
            </div>
        </div>

        <!-- List -->
        <div class="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
            <div *ngIf="filteredVerifications.length > 0; else noData" class="divide-y divide-gray-200">
                <div *ngFor="let v of filteredVerifications" class="p-6 hover:bg-gray-50 transition-colors">
                    <div class="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
                        <div class="flex-1 min-w-0">
                            <div class="flex items-center gap-3 mb-2">
                                <h3 class="text-lg font-semibold text-gray-900 truncate">{{ getUserName(v) }}</h3>
                                <span class="inline-flex px-2 py-1 text-xs font-semibold rounded-full"
                                    [ngClass]="getStatusColor(v.status)">
                                    {{ v.status | titlecase }}
                                </span>
                            </div>
                            <p class="text-sm text-gray-500 mb-3">{{ getUserEmail(v) }}</p>

                            <div class="grid grid-cols-2 sm:grid-cols-3 gap-4">
                                <div>
                                    <p class="text-xs text-gray-500 uppercase">Type</p>
                                    <p class="text-sm font-medium capitalize">{{ v.verification_type }}</p>
                                </div>
                                <div>
                                    <p class="text-xs text-gray-500 uppercase">Document</p>
                                    <p class="text-sm font-medium capitalize">{{ v.document_type }}</p>
                                </div>
                                <div>
                                    <p class="text-xs text-gray-500 uppercase">Submitted</p>
                                    <p class="text-sm font-medium">{{ v.created_at | date:'shortDate' }}</p>
                                </div>
                            </div>
                        </div>
                        <button (click)="handleViewVerification(v)"
                            class="flex items-center px-4 py-2 text-sm font-medium text-primary-600 bg-primary-50 border border-primary-200 rounded-lg hover:bg-primary-100">
                            <lucide-icon [img]="EyeIcon" class="h-4 w-4 mr-2"></lucide-icon>
                            Review
                        </button>
                    </div>
                </div>
            </div>
            <ng-template #noData>
                <div class="text-center py-12">
                    <lucide-icon [img]="FileTextIcon" class="h-12 w-12 text-gray-400 mx-auto mb-4"></lucide-icon>
                    <p class="text-gray-600">No verifications found</p>
                </div>
            </ng-template>
        </div>
    </div>

    <!-- Modal -->
    <div *ngIf="reviewModalOpen && selectedVerification"
        class="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center p-4" (click)="closeModal()">
        <div class="bg-white rounded-lg shadow-xl max-w-4xl w-full max-h-[90vh] overflow-y-auto"
            (click)="$event.stopPropagation()">
            <div class="p-6 border-b border-gray-200 flex justify-between items-center">
                <h2 class="text-2xl font-bold text-gray-900">Review Verification</h2>
                <button (click)="closeModal()" class="text-gray-400 hover:text-gray-600">
                    <lucide-icon [img]="XCircleIcon" class="h-6 w-6"></lucide-icon>
                </button>
            </div>

            <div class="p-6 space-y-6">
                <!-- Info -->
                <div class="bg-gray-50 rounded-lg p-4 grid grid-cols-2 gap-4">
                    <div>
                        <p class="text-gray-500 text-sm">Name</p>
                        <p class="font-medium">{{ getUserName(selectedVerification) }}</p>
                    </div>
                    <div>
                        <p class="text-gray-500 text-sm">Email</p>
                        <p class="font-medium">{{ getUserEmail(selectedVerification) }}</p>
                    </div>
                </div>

                <!-- Document -->
                <div class="border rounded-lg p-4 bg-gray-50 min-h-[200px] flex items-center justify-center">
                    <div *ngIf="loadingDocument">
                        <lucide-icon [img]="Loader2Icon" class="h-8 w-8 animate-spin text-primary-600"></lucide-icon>
                    </div>
                    <div *ngIf="!loadingDocument && documentUrl">
                        <img *ngIf="selectedVerification.mime_type?.startsWith('image/')" [src]="documentUrl"
                            class="max-w-full rounded border">
                        <div *ngIf="!selectedVerification.mime_type?.startsWith('image/')" class="text-center">
                            <p class="mb-4">{{ selectedVerification.document_name }}</p>
                            <a [href]="documentUrl" target="_blank"
                                class="px-4 py-2 bg-primary-50 text-primary-600 rounded-lg border border-primary-200">Download</a>
                        </div>
                    </div>
                    <div *ngIf="!loadingDocument && !documentUrl">Failed to load document</div>
                </div>

                <!-- Actions -->
                <div class="space-y-4">
                    <h3 class="font-semibold">Action</h3>
                    <div class="grid grid-cols-2 gap-4">
                        <button (click)="reviewData.action = 'approve'"
                            class="p-4 border-2 rounded-lg flex items-center gap-3"
                            [class.border-green-500]="reviewData.action === 'approve'"
                            [class.bg-green-50]="reviewData.action === 'approve'">
                            <lucide-icon [img]="CheckCircleIcon"
                                [class.text-green-600]="reviewData.action === 'approve'"
                                class="h-6 w-6 text-gray-400"></lucide-icon>
                            <div class="text-left">
                                <p class="font-bold">Approve</p>
                                <p class="text-sm text-gray-500">Verify identity</p>
                            </div>
                        </button>
                        <button (click)="reviewData.action = 'reject'"
                            class="p-4 border-2 rounded-lg flex items-center gap-3"
                            [class.border-red-500]="reviewData.action === 'reject'"
                            [class.bg-red-50]="reviewData.action === 'reject'">
                            <lucide-icon [img]="XCircleIcon" [class.text-red-600]="reviewData.action === 'reject'"
                                class="h-6 w-6 text-gray-400"></lucide-icon>
                            <div class="text-left">
                                <p class="font-bold">Reject</p>
                                <p class="text-sm text-gray-500">Do not verify</p>
                            </div>
                        </button>
                    </div>

                    <div *ngIf="reviewData.action === 'reject'">
                        <label class="block mb-2 font-medium">Reason *</label>
                        <textarea [(ngModel)]="reviewData.rejectionReason" class="w-full border rounded-lg p-2"
                            rows="3"></textarea>
                    </div>
                </div>
            </div>

            <div class="p-6 border-t bg-gray-50 flex justify-end gap-3">
                <button (click)="closeModal()" class="px-4 py-2 border rounded-lg bg-white">Cancel</button>
                <button (click)="handleReview()" [disabled]="processing || !reviewData.action"
                    class="px-4 py-2 rounded-lg text-white"
                    [ngClass]="{'bg-green-600': reviewData.action === 'approve', 'bg-red-600': reviewData.action === 'reject', 'bg-gray-400': !reviewData.action}">
                    <span *ngIf="processing">Processing...</span>
                    <span *ngIf="!processing">Confirm {{ reviewData.action | titlecase }}</span>
                </button>
            </div>
        </div>
    </div>
</div>

// src-react-backup/pages/AdminVerificationReview.js
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  Shield, 
  CheckCircle, 
  XCircle, 
  Clock, 
  FileText, 
  Eye, 
  Loader2,
  RefreshCw,
  Search,
  Filter,
  Download,
  AlertCircle
} from 'lucide-react';
import { auth } from '../lib/supabase';
import { verificationService } from '../services/verificationService';
import { storageService } from '../services/storageService';
import { useToast } from '../contexts/ToastContext';

const AdminVerificationReview = () => {
  const navigate = useNavigate();
  const { success, error: showError, warning } = useToast();
  const [loading, setLoading] = useState(true);
  const [user, setUser] = useState(null);
  const [isAdmin, setIsAdmin] = useState(false);
  const [verifications, setVerifications] = useState([]);
  const [filteredVerifications, setFilteredVerifications] = useState([]);
  const [selectedVerification, setSelectedVerification] = useState(null);
  const [reviewModalOpen, setReviewModalOpen] = useState(false);
  const [reviewData, setReviewData] = useState({
    action: '', // 'approve' or 'reject'
    rejectionReason: '',
    adminNotes: ''
  });
  const [documentUrl, setDocumentUrl] = useState(null);
  const [loadingDocument, setLoadingDocument] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState('pending');
  const [processing, setProcessing] = useState(false);

  useEffect(() => {
    const checkAdminAccess = async () => {
      try {
        const { user, error } = await auth.getCurrentUser();
        if (error || !user) {
          navigate('/login');
          return;
        }

        setUser(user);
        
        // Check if user is admin
        const adminStatus = user.user_metadata?.role === 'Administrator' || user.user_metadata?.role === 'Admin';
        setIsAdmin(adminStatus);
        
        if (!adminStatus) {
          navigate('/dashboard');
          return;
        }

        await loadVerifications();
      } catch (error) {
        console.error('Error checking admin access:', error);
        navigate('/login');
      } finally {
        setLoading(false);
      }
    };

    checkAdminAccess();
  }, [navigate]);

  const loadVerifications = async () => {
    try {
      setLoading(true);
      const { data, error } = await verificationService.getPendingVerifications({
        status: statusFilter === 'all' ? 'all' : statusFilter,
        limit: 100
      });

      if (error) throw error;
      setVerifications(data || []);
      setFilteredVerifications(data || []);
    } catch (error) {
      console.error('Error loading verifications:', error);
      setVerifications([]);
      setFilteredVerifications([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    let filtered = verifications;

    if (searchQuery) {
      filtered = filtered.filter(verification => 
        verification.users?.email?.toLowerCase().includes(searchQuery.toLowerCase()) ||
        verification.verification_type?.toLowerCase().includes(searchQuery.toLowerCase()) ||
        verification.document_type?.toLowerCase().includes(searchQuery.toLowerCase())
      );
    }

    setFilteredVerifications(filtered);
  }, [verifications, searchQuery]);

  useEffect(() => {
    loadVerifications();
  }, [statusFilter]);

  const handleViewVerification = async (verification) => {
    setSelectedVerification(verification);
    setReviewModalOpen(true);
    setLoadingDocument(true);
    setDocumentUrl(null);

    try {
      // Get signed URL for the document
      const { data: url, error } = await storageService.getVerificationDocumentUrl(
        verification.file_path,
        3600 // 1 hour expiry
      );

      if (error) throw error;
      setDocumentUrl(url);
    } catch (error) {
      console.error('Error loading document:', error);
      showError('Unable to load the verification document at this time. Please try again later.');
    } finally {
      setLoadingDocument(false);
    }
  };

  const handleReview = async () => {
    if (!selectedVerification || !reviewData.action) {
      warning('Please select an action: Approve or Reject.');
      return;
    }

    if (reviewData.action === 'reject' && !reviewData.rejectionReason.trim()) {
      warning('Please provide a reason for rejecting this verification.');
      return;
    }

    setProcessing(true);
    try {
      if (reviewData.action === 'approve') {
        const { error } = await verificationService.approveVerification(
          selectedVerification.id,
          user.id,
          reviewData.adminNotes || null
        );
        if (error) throw error;
      } else {
        const { error } = await verificationService.rejectVerification(
          selectedVerification.id,
          user.id,
          reviewData.rejectionReason,
          reviewData.adminNotes || null
        );
        if (error) throw error;
      }

      // Reload verifications
      await loadVerifications();
      
      // Close modal and reset
      setReviewModalOpen(false);
      setSelectedVerification(null);
      setReviewData({
        action: '',
        rejectionReason: '',
        adminNotes: ''
      });
      setDocumentUrl(null);
      
      success(`Verification has been ${reviewData.action === 'approve' ? 'approved' : 'rejected'} successfully.`);
    } catch (error) {
      console.error('Error reviewing verification:', error);
      showError(`Unable to ${reviewData.action} verification at this time. Please try again later.`);
    } finally {
      setProcessing(false);
    }
  };

  const getStatusColor = (status) => {
    switch (status) {
      case 'approved': return 'bg-green-100 text-green-800';
      case 'rejected': return 'bg-red-100 text-red-800';
      case 'pending': return 'bg-yellow-100 text-yellow-800';
      case 'under_review': return 'bg-blue-100 text-blue-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  const getStatusIcon = (status) => {
    switch (status) {
      case 'approved': return <CheckCircle size={16} className="text-green-600" />;
      case 'rejected': return <XCircle size={16} className="text-red-600" />;
      case 'pending': return <Clock size={16} className="text-yellow-600" />;
      case 'under_review': return <AlertCircle size={16} className="text-blue-600" />;
      default: return <FileText size={16} className="text-gray-600" />;
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center">
          <Loader2 className="h-12 w-12 animate-spin text-primary-600 mx-auto mb-4" />
          <p className="text-gray-600">Loading verifications...</p>
        </div>
      </div>
    );
  }

  if (!isAdmin) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center">
          <Shield className="h-16 w-16 text-red-500 mx-auto mb-4" />
          <h2 className="text-2xl font-bold text-gray-900 mb-2">Access Denied</h2>
          <p className="text-gray-600">You don't have permission to access verification review.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white shadow-sm border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-3 sm:px-6 lg:px-8">
          <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center py-4 sm:py-6 gap-3 sm:gap-0">
            <div className="min-w-0">
              <h1 className="text-xl sm:text-3xl font-bold text-gray-900 truncate">Verification Review</h1>
              <p className="text-sm sm:text-base text-gray-600 mt-0.5 sm:mt-1">Review and approve/reject user verification documents</p>
            </div>
            <div className="flex items-center flex-shrink-0">
              <button
                onClick={loadVerifications}
                className="flex items-center px-3 sm:px-4 py-1.5 sm:py-2 text-xs sm:text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
              >
                <RefreshCw className="h-3.5 w-3.5 sm:h-4 sm:w-4 mr-1.5 sm:mr-2" />
                Refresh
              </button>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-3 sm:px-6 lg:px-8 py-4 sm:py-8">
        {/* Filters */}
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-3 sm:p-4 mb-4 sm:mb-6">
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3 sm:gap-4">
            <div>
              <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1.5 sm:mb-2">Search</label>
              <div className="relative">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" size={16} />
                <input
                  type="text"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  placeholder="Search by email, type..."
                  className="w-full pl-9 sm:pl-10 pr-3 sm:pr-4 py-2 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                />
              </div>
            </div>
            <div>
              <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1.5 sm:mb-2">Status Filter</label>
              <select
                value={statusFilter}
                onChange={(e) => setStatusFilter(e.target.value)}
                className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
              >
                <option value="pending">Pending</option>
                <option value="under_review">Under Review</option>
                <option value="all">All</option>
              </select>
            </div>
            <div className="flex items-end sm:col-span-2 md:col-span-1">
              <div className="text-xs sm:text-sm text-gray-600">
                <span className="font-medium">{filteredVerifications.length}</span> verification{filteredVerifications.length !== 1 ? 's' : ''} found
              </div>
            </div>
          </div>
        </div>

        {/* Verifications List */}
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
          {filteredVerifications.length > 0 ? (
            <div className="divide-y divide-gray-200">
              {filteredVerifications.map((verification) => (
                <div key={verification.id} className="p-3 sm:p-6 hover:bg-gray-50 transition-colors">
                  <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3 sm:gap-0">
                    <div className="flex-1 min-w-0">
                      <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:space-x-3 mb-2">
                        <div className="min-w-0">
                          <h3 className="text-base sm:text-lg font-semibold text-gray-900 truncate">
                            {verification.users?.name || verification.users?.email || verification.user_id?.substring(0, 8) || 'Unknown User'}
                          </h3>
                          {verification.users?.email && verification.users?.name && (
                            <p className="text-xs sm:text-sm text-gray-500 truncate">{verification.users.email}</p>
                          )}
                        </div>
                        <span className={`inline-flex items-center px-2 py-0.5 sm:py-1 text-xs font-semibold rounded-full flex-shrink-0 w-fit ${getStatusColor(verification.status)}`}>
                          {getStatusIcon(verification.status)}
                          <span className="ml-1 capitalize">{verification.status.replace('_', ' ')}</span>
                        </span>
                      </div>
                      
                      <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 sm:gap-4 mt-3 sm:mt-4">
                        <div>
                          <p className="text-xs text-gray-500 uppercase tracking-wide">Type</p>
                          <p className="text-xs sm:text-sm font-medium text-gray-900 capitalize truncate">{verification.verification_type}</p>
                        </div>
                        <div>
                          <p className="text-xs text-gray-500 uppercase tracking-wide">Document</p>
                          <p className="text-xs sm:text-sm font-medium text-gray-900 capitalize truncate">{verification.document_type.replace('_', ' ')}</p>
                        </div>
                        <div className="col-span-2 sm:col-span-1">
                          <p className="text-xs text-gray-500 uppercase tracking-wide">Submitted</p>
                          <p className="text-xs sm:text-sm font-medium text-gray-900">
                            {new Date(verification.created_at).toLocaleDateString()}
                          </p>
                        </div>
                      </div>

                      {verification.rejection_reason && (
                        <div className="mt-2 sm:mt-3 p-2 sm:p-3 bg-red-50 border border-red-200 rounded-lg">
                          <p className="text-xs text-red-600 font-medium mb-0.5 sm:mb-1">Previous Rejection Reason:</p>
                          <p className="text-xs sm:text-sm text-red-800">{verification.rejection_reason}</p>
                        </div>
                      )}
                    </div>

                    <div className="sm:ml-4 flex items-center">
                      <button
                        onClick={() => handleViewVerification(verification)}
                        className="w-full sm:w-auto flex items-center justify-center px-3 sm:px-4 py-1.5 sm:py-2 text-xs sm:text-sm font-medium text-primary-600 bg-primary-50 border border-primary-200 rounded-lg hover:bg-primary-100 transition-colors"
                      >
                        <Eye className="h-3.5 w-3.5 sm:h-4 sm:w-4 mr-1.5 sm:mr-2" />
                        Review
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="text-center py-12">
              <FileText className="h-12 w-12 text-gray-400 mx-auto mb-4" />
              <p className="text-gray-600 mb-2">No verifications found</p>
              <p className="text-sm text-gray-500">
                {statusFilter === 'pending' 
                  ? 'No pending verifications at this time.'
                  : 'No verifications match your search criteria.'}
              </p>
            </div>
          )}
        </div>
      </div>

      {/* Review Modal */}
      {reviewModalOpen && selectedVerification && (
        <div 
          className="fixed inset-0 bg-black bg-opacity-50 z-[100] flex items-center justify-center p-4"
          onClick={(e) => {
            if (e.target === e.currentTarget) {
              setReviewModalOpen(false);
              setSelectedVerification(null);
              setDocumentUrl(null);
              setReviewData({
                action: '',
                rejectionReason: '',
                adminNotes: ''
              });
            }
          }}
        >
          <div 
            className="bg-white rounded-lg shadow-xl max-w-4xl w-full max-h-[90vh] overflow-y-auto relative mx-2 sm:mx-4"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="p-4 sm:p-6 border-b border-gray-200">
              <div className="flex items-center justify-between">
                <h2 className="text-lg sm:text-2xl font-bold text-gray-900">Review Verification</h2>
                <button
                  onClick={() => {
                    setReviewModalOpen(false);
                    setSelectedVerification(null);
                    setDocumentUrl(null);
                    setReviewData({
                      action: '',
                      rejectionReason: '',
                      adminNotes: ''
                    });
                  }}
                  className="text-gray-400 hover:text-gray-600"
                >
                  <XCircle size={20} />
                </button>
              </div>
            </div>

            <div className="p-4 sm:p-6 space-y-4 sm:space-y-6">
              {/* User Information */}
              <div className="bg-gray-50 rounded-lg p-3 sm:p-4">
                <h3 className="font-semibold text-gray-900 text-sm sm:text-base mb-2 sm:mb-3">User Information</h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4 text-xs sm:text-sm">
                  <div>
                    <p className="text-gray-500">Name</p>
                    <p className="font-medium text-gray-900 break-words">{selectedVerification.users?.name || 'N/A'}</p>
                  </div>
                  <div>
                    <p className="text-gray-500">Email</p>
                    <p className="font-medium text-gray-900 break-all">{selectedVerification.users?.email || 'N/A'}</p>
                  </div>
                  <div>
                    <p className="text-gray-500">Verification Type</p>
                    <p className="font-medium text-gray-900 capitalize">{selectedVerification.verification_type}</p>
                  </div>
                  <div>
                    <p className="text-gray-500">Document Type</p>
                    <p className="font-medium text-gray-900 capitalize">{selectedVerification.document_type.replace('_', ' ')}</p>
                  </div>
                  <div className="sm:col-span-2">
                    <p className="text-gray-500">Submitted</p>
                    <p className="font-medium text-gray-900">
                      {new Date(selectedVerification.created_at).toLocaleString()}
                    </p>
                  </div>
                </div>
              </div>

              {/* Document Preview */}
              <div>
                <h3 className="font-semibold text-gray-900 mb-3">Verification Document</h3>
                <div className="border border-gray-200 rounded-lg p-4 bg-gray-50">
                  {loadingDocument ? (
                    <div className="flex items-center justify-center py-12">
                      <Loader2 className="h-8 w-8 animate-spin text-primary-600" />
                    </div>
                  ) : documentUrl ? (
                    <div className="space-y-4">
                      {selectedVerification.mime_type?.startsWith('image/') ? (
                        <img
                          src={documentUrl}
                          alt="Verification document"
                          className="max-w-full h-auto mx-auto rounded-lg border border-gray-200"
                        />
                      ) : (
                        <div className="text-center py-8">
                          <FileText className="h-16 w-16 text-gray-400 mx-auto mb-4" />
                          <p className="text-sm text-gray-600 mb-4">
                            {selectedVerification.document_name}
                          </p>
                          <a
                            href={documentUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="inline-flex items-center px-4 py-2 text-sm font-medium text-primary-600 bg-primary-50 border border-primary-200 rounded-lg hover:bg-primary-100"
                          >
                            <Download className="h-4 w-4 mr-2" />
                            Download Document
                          </a>
                        </div>
                      )}
                    </div>
                  ) : (
                    <div className="text-center py-8 text-gray-500">
                      <p>Failed to load document</p>
                    </div>
                  )}
                </div>
              </div>

              {/* Review Actions */}
              <div className="space-y-3 sm:space-y-4">
                <h3 className="font-semibold text-gray-900 text-sm sm:text-base">Review Action</h3>
                
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 sm:gap-4">
                  <button
                    onClick={() => setReviewData(prev => ({ ...prev, action: 'approve' }))}
                    className={`p-3 sm:p-4 border-2 rounded-lg transition-colors ${
                      reviewData.action === 'approve'
                        ? 'border-green-500 bg-green-50'
                        : 'border-gray-200 hover:border-green-300'
                    }`}
                  >
                    <div className="flex items-center space-x-2 sm:space-x-3">
                      <CheckCircle className={`h-5 w-5 sm:h-6 sm:w-6 flex-shrink-0 ${reviewData.action === 'approve' ? 'text-green-600' : 'text-gray-400'}`} />
                      <div className="text-left min-w-0">
                        <p className="font-semibold text-gray-900 text-sm sm:text-base">Approve</p>
                        <p className="text-xs sm:text-sm text-gray-500">Verify this user's identity</p>
                      </div>
                    </div>
                  </button>

                  <button
                    onClick={() => setReviewData(prev => ({ ...prev, action: 'reject' }))}
                    className={`p-3 sm:p-4 border-2 rounded-lg transition-colors ${
                      reviewData.action === 'reject'
                        ? 'border-red-500 bg-red-50'
                        : 'border-gray-200 hover:border-red-300'
                    }`}
                  >
                    <div className="flex items-center space-x-2 sm:space-x-3">
                      <XCircle className={`h-5 w-5 sm:h-6 sm:w-6 flex-shrink-0 ${reviewData.action === 'reject' ? 'text-red-600' : 'text-gray-400'}`} />
                      <div className="text-left min-w-0">
                        <p className="font-semibold text-gray-900 text-sm sm:text-base">Reject</p>
                        <p className="text-xs sm:text-sm text-gray-500">Reject this verification</p>
                      </div>
                    </div>
                  </button>
                </div>

                {reviewData.action === 'reject' && (
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Rejection Reason *
                    </label>
                    <textarea
                      value={reviewData.rejectionReason}
                      onChange={(e) => setReviewData(prev => ({ ...prev, rejectionReason: e.target.value }))}
                      rows={3}
                      className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                      placeholder="Please provide a clear reason for rejection so the user can resubmit with correct documents..."
                      required
                    />
                  </div>
                )}

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Admin Notes (Optional)
                  </label>
                  <textarea
                    value={reviewData.adminNotes}
                    onChange={(e) => setReviewData(prev => ({ ...prev, adminNotes: e.target.value }))}
                    rows={2}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                    placeholder="Internal notes (not visible to user)..."
                  />
                </div>
              </div>
            </div>

            <div className="p-4 sm:p-6 border-t border-gray-200 flex flex-col sm:flex-row sm:justify-end gap-2 sm:space-x-3 sm:gap-0">
              <button
                onClick={() => {
                  setReviewModalOpen(false);
                  setSelectedVerification(null);
                  setDocumentUrl(null);
                  setReviewData({
                    action: '',
                    rejectionReason: '',
                    adminNotes: ''
                  });
                }}
                className="w-full sm:w-auto px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 order-2 sm:order-1"
                disabled={processing}
              >
                Cancel
              </button>
              <button
                onClick={handleReview}
                disabled={processing || !reviewData.action || (reviewData.action === 'reject' && !reviewData.rejectionReason.trim())}
                className={`w-full sm:w-auto px-4 py-2 text-sm font-medium text-white rounded-lg order-1 sm:order-2 ${
                  reviewData.action === 'approve'
                    ? 'bg-green-600 hover:bg-green-700'
                    : 'bg-red-600 hover:bg-red-700'
                } disabled:opacity-50 disabled:cursor-not-allowed`}
              >
                {processing ? (
                  <div className="flex items-center justify-center">
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    Processing...
                  </div>
                ) : (
                  reviewData.action === 'approve' ? 'Approve Verification' : 'Reject Verification'
                )}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AdminVerificationReview;
