// src/app/features/admin/pages/admin-event-management/admin-event-management.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { EventsService } from '../../../../core/services/events.service';
import { AuthService } from '../../../../core/services/auth.service';
import { LucideAngularModule, Calendar, Edit, Eye, Users, MapPin, Clock, Shield, Loader2, RefreshCw, BarChart3, Search, Filter } from 'lucide-angular';

@Component({
  selector: 'app-admin-event-management',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule, LucideAngularModule],
  templateUrl: './admin-event-management.component.html',
  styleUrl: './admin-event-management.component.css'
})
export class AdminEventManagementComponent implements OnInit {
  loading = true;
  isAdmin = false;
  events: any[] = [];
  filteredEvents: any[] = [];
  participantCounts: { [key: string]: number } = {};

  // Search & Filter
  searchQuery = '';
  statusFilter = 'all';

  // Icons
  readonly CalendarIcon = Calendar;
  readonly EditIcon = Edit;
  readonly EyeIcon = Eye;
  readonly UsersIcon = Users;
  readonly MapPinIcon = MapPin;
  readonly ClockIcon = Clock;
  readonly ShieldIcon = Shield;
  readonly Loader2Icon = Loader2;
  readonly RefreshCwIcon = RefreshCw;
  readonly BarChart3Icon = BarChart3;
  readonly SearchIcon = Search;
  readonly FilterIcon = Filter;

  constructor(
    private eventsService: EventsService,
    private authService: AuthService,
    private router: Router
  ) { }

  async ngOnInit() {
    const user = await this.authService.getCurrentUser();
    const role = user?.user_metadata?.role;
    this.isAdmin = role === 'admin' || role === 'Admin' || role === 'Administrator';

    if (!this.isAdmin) {
      this.loading = false;
      return;
    }

    await this.loadEvents();
  }

  async loadEvents() {
    try {
      this.loading = true;
      const { data, error } = await this.eventsService.getAllEvents();
      if (error) throw error;

      this.events = data || [];
      this.applyFilters();

      // Load participant counts
      // We'll do this in the background to avoid blocking UI too long if list is huge,
      // but strictly we should probably wait or use the existing patterns.
      // We will perform it now.
      const counts: { [key: string]: number } = {};

      // Parallelize requests for speed
      const promises = this.events.map(event =>
        this.eventsService.getEventParticipants(event.id)
          .then(res => ({ id: event.id, count: res.data || 0 }))
      );

      const results = await Promise.all(promises);
      results.forEach(r => counts[r.id] = r.count);

      this.participantCounts = counts;

    } catch (error) {
      console.error('Error loading events:', error);
    } finally {
      this.loading = false;
    }
  }

  applyFilters() {
    let filtered = this.events;

    if (this.searchQuery) {
      const q = this.searchQuery.toLowerCase();
      filtered = filtered.filter(event =>
        event.title.toLowerCase().includes(q) ||
        (event.description && event.description.toLowerCase().includes(q)) ||
        (event.location && event.location.toLowerCase().includes(q))
      );
    }

    if (this.statusFilter !== 'all') {
      filtered = filtered.filter(event => event.status === this.statusFilter);
    }

    this.filteredEvents = filtered;
  }

  onSearch() {
    this.applyFilters();
  }

  onFilterChange() {
    this.applyFilters();
  }

  getStatusColor(status: string): string {
    switch (status?.toLowerCase()) {
      case 'upcoming': return 'bg-blue-100 text-blue-800';
      case 'ongoing': return 'bg-yellow-100 text-yellow-800';
      case 'completed': return 'bg-green-100 text-green-800';
      case 'cancelled': return 'bg-red-100 text-red-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  }

  getParticipantPercentage(current: number, max: number): number {
    if (!max || max === 0) return 0;
    return Math.round((current / max) * 100);
  }

  get totalParticipants(): number {
    return Object.values(this.participantCounts).reduce((a, b) => a + b, 0);
  }

  get activeEventsCount(): number {
    return this.events.filter(e => e.status === 'ongoing').length;
  }

  get averageAttendance(): number {
    if (this.events.length === 0) return 0;
    return Math.round(this.totalParticipants / this.events.length);
  }
}

<div *ngIf="loading" class="flex items-center justify-center min-h-screen">
    <div class="text-center">
        <lucide-icon [img]="Loader2Icon" class="h-12 w-12 animate-spin text-primary-600 mx-auto mb-4"></lucide-icon>
        <p class="text-gray-600">Loading event management...</p>
    </div>
</div>

<div *ngIf="!loading && !isAdmin" class="flex items-center justify-center min-h-screen">
    <div class="text-center">
        <lucide-icon [img]="ShieldIcon" class="h-16 w-16 text-red-500 mx-auto mb-4"></lucide-icon>
        <h2 class="text-2xl font-bold text-gray-900 mb-2">Access Denied</h2>
        <p class="text-gray-600">You don't have permission to access event management.</p>
    </div>
</div>

<div *ngIf="!loading && isAdmin" class="min-h-screen bg-gray-50">
    <!-- Header -->
    <div class="bg-white shadow-sm border-b border-gray-200">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4 py-4 sm:py-6">
                <div class="min-w-0">
                    <h1 class="text-2xl sm:text-3xl font-bold text-gray-900">Event Management</h1>
                    <p class="text-sm sm:text-base text-gray-600 mt-1">Oversee all platform events and activities</p>
                </div>
                <div class="flex items-center">
                    <button (click)="loadEvents()"
                        class="flex items-center justify-center px-3 sm:px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors">
                        <lucide-icon [img]="RefreshCwIcon" class="h-4 w-4 sm:mr-2"></lucide-icon>
                        <span class="hidden sm:inline">Refresh</span>
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 sm:py-8">
        <!-- Statistics -->
        <div class="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-6 mb-4 sm:mb-8">
            <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-3 sm:p-6">
                <div class="flex items-center gap-2 sm:gap-4">
                    <div class="p-2 sm:p-3 bg-blue-100 rounded-full flex-shrink-0">
                        <lucide-icon [img]="CalendarIcon" class="h-4 w-4 sm:h-6 sm:w-6 text-blue-600"></lucide-icon>
                    </div>
                    <div class="min-w-0">
                        <p class="text-xs sm:text-sm font-medium text-gray-600 truncate">Total Events</p>
                        <p class="text-lg sm:text-2xl font-bold text-gray-900">{{ events.length }}</p>
                    </div>
                </div>
            </div>

            <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-3 sm:p-6">
                <div class="flex items-center gap-2 sm:gap-4">
                    <div class="p-2 sm:p-3 bg-yellow-100 rounded-full flex-shrink-0">
                        <lucide-icon [img]="ClockIcon" class="h-4 w-4 sm:h-6 sm:w-6 text-yellow-600"></lucide-icon>
                    </div>
                    <div class="min-w-0">
                        <p class="text-xs sm:text-sm font-medium text-gray-600 truncate">Active</p>
                        <p class="text-lg sm:text-2xl font-bold text-gray-900">{{ activeEventsCount }}</p>
                    </div>
                </div>
            </div>

            <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-3 sm:p-6">
                <div class="flex items-center gap-2 sm:gap-4">
                    <div class="p-2 sm:p-3 bg-green-100 rounded-full flex-shrink-0">
                        <lucide-icon [img]="UsersIcon" class="h-4 w-4 sm:h-6 sm:w-6 text-green-600"></lucide-icon>
                    </div>
                    <div class="min-w-0">
                        <p class="text-xs sm:text-sm font-medium text-gray-600 truncate">Participants</p>
                        <p class="text-lg sm:text-2xl font-bold text-gray-900">{{ totalParticipants }}</p>
                    </div>
                </div>
            </div>

            <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-3 sm:p-6">
                <div class="flex items-center gap-2 sm:gap-4">
                    <div class="p-2 sm:p-3 bg-purple-100 rounded-full flex-shrink-0">
                        <lucide-icon [img]="BarChart3Icon" class="h-4 w-4 sm:h-6 sm:w-6 text-purple-600"></lucide-icon>
                    </div>
                    <div class="min-w-0">
                        <p class="text-xs sm:text-sm font-medium text-gray-600 truncate">Avg. Attend</p>
                        <p class="text-lg sm:text-2xl font-bold text-gray-900">{{ averageAttendance }}</p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Filters -->
        <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-4 mb-6">
            <div class="flex flex-col sm:flex-row gap-4">
                <div class="flex-1 relative">
                    <lucide-icon [img]="SearchIcon"
                        class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-5 w-5"></lucide-icon>
                    <input type="text" [(ngModel)]="searchQuery" (ngModelChange)="onSearch()"
                        placeholder="Search events..."
                        class="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500">
                </div>
                <div class="w-full sm:w-48">
                    <select [(ngModel)]="statusFilter" (ngModelChange)="onFilterChange()"
                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500">
                        <option value="all">All Status</option>
                        <option value="upcoming">Upcoming</option>
                        <option value="ongoing">Ongoing</option>
                        <option value="completed">Completed</option>
                        <option value="cancelled">Cancelled</option>
                    </select>
                </div>
            </div>
        </div>

        <!-- Events Table -->
        <div class="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
            <div class="overflow-x-auto">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Event</th>
                            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Status</th>
                            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Date & Time</th>
                            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Location</th>
                            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Participants</th>
                            <th class="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Actions</th>
                        </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                        <tr *ngFor="let event of filteredEvents" class="hover:bg-gray-50">
                            <td class="px-6 py-4 whitespace-nowrap">
                                <div class="flex items-center">
                                    <div class="flex-shrink-0 h-12 w-12">
                                        <img class="h-12 w-12 rounded-lg object-cover"
                                            [src]="event.image_url || 'assets/placeholder-event.jpg'"
                                            [alt]="event.title">
                                    </div>
                                    <div class="ml-4">
                                        <div class="text-sm font-medium text-gray-900 line-clamp-1">{{ event.title }}
                                        </div>
                                        <div class="text-sm text-gray-500 line-clamp-1">{{ event.description }}</div>
                                    </div>
                                </div>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap">
                                <span class="inline-flex px-2 py-1 text-xs font-semibold rounded-full"
                                    [ngClass]="getStatusColor(event.status)">
                                    {{ event.status | titlecase }}
                                </span>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                <div class="flex items-center">
                                    <lucide-icon [img]="CalendarIcon" class="h-4 w-4 mr-2 text-gray-400"></lucide-icon>
                                    {{ event.date | date:'mediumDate' }}
                                </div>
                                <div *ngIf="event.time" class="flex items-center text-sm text-gray-500 mt-1">
                                    <lucide-icon [img]="ClockIcon" class="h-4 w-4 mr-2 text-gray-400"></lucide-icon>
                                    {{ event.time }}
                                </div>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                <div class="flex items-center">
                                    <lucide-icon [img]="MapPinIcon" class="h-4 w-4 mr-2 text-gray-400"></lucide-icon>
                                    {{ event.location }}
                                </div>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap">
                                <div class="flex items-center">
                                    <div class="flex-1 w-32">
                                        <div class="text-sm text-gray-900">
                                            {{ participantCounts[event.id] || 0 }}/{{ event.max_participants || '∞' }}
                                        </div>
                                        <div class="w-full bg-gray-200 rounded-full h-2 mt-1">
                                            <div class="bg-primary-600 h-2 rounded-full transition-all duration-300"
                                                [style.width.%]="getParticipantPercentage(participantCounts[event.id] || 0, event.max_participants)">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                <div class="flex items-center justify-end space-x-2">
                                    <button [routerLink]="['/events', event.id]"
                                        class="text-primary-600 hover:text-primary-900" title="View Event">
                                        <lucide-icon [img]="EyeIcon" class="h-4 w-4"></lucide-icon>
                                    </button>
                                    <button [routerLink]="['/events', event.id, 'edit']"
                                        class="text-blue-600 hover:text-blue-900" title="Edit Event">
                                        <lucide-icon [img]="EditIcon" class="h-4 w-4"></lucide-icon>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div *ngIf="filteredEvents.length === 0" class="text-center py-12">
                <lucide-icon [img]="CalendarIcon" class="h-12 w-12 text-gray-400 mx-auto mb-4"></lucide-icon>
                <h3 class="text-lg font-medium text-gray-900 mb-2">No events found</h3>
                <p class="text-gray-600">Try adjusting your search or filter criteria.</p>
            </div>
        </div>
    </div>
</div>

// src-react-backup/pages/AdminEventManagement.js
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  Calendar, 
  Edit, 
  Eye, 
  Users,
  MapPin,
  Clock,
  Shield,
  Loader2,
  RefreshCw,
  BarChart3
} from 'lucide-react';
import { auth } from '../lib/supabase';
import { eventsService } from '../services/eventsService';

const AdminEventManagement = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true);
  const [user, setUser] = useState(null);
  const [isAdmin, setIsAdmin] = useState(false);
  const [events, setEvents] = useState([]);
  const [filteredEvents, setFilteredEvents] = useState([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  const [participantCounts, setParticipantCounts] = useState({});

  useEffect(() => {
    const checkAdminAccess = async () => {
      try {
        const { user, error } = await auth.getCurrentUser();
        if (error || !user) {
          navigate('/login');
          return;
        }

        setUser(user);
        
        // Check if user is admin
        const adminStatus = user.user_metadata?.role === 'Administrator' || user.user_metadata?.role === 'Admin';
        setIsAdmin(adminStatus);
        
        if (!adminStatus) {
          navigate('/dashboard');
          return;
        }

        await loadEvents();
      } catch (error) {
        console.error('Error checking admin access:', error);
        navigate('/login');
      } finally {
        setLoading(false);
      }
    };

    checkAdminAccess();
  }, [navigate]);

  const loadEvents = async () => {
    try {
      setLoading(true);
      const { data, error } = await eventsService.getAllEvents();
      
      if (error) throw error;
      
      setEvents(data || []);
      
      // Load participant counts for each event
      if (data && data.length > 0) {
        const counts = {};
        for (const event of data) {
          const { data: count, error } = await eventsService.getEventParticipants(event.id);
          if (error) {
            console.error('Error loading participants for event', event.id, ':', error);
          }
          counts[event.id] = count || 0;
        }
        setParticipantCounts(counts);
      }
    } catch (error) {
      console.error('Error loading events:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    let filtered = events;

    if (searchQuery) {
      filtered = filtered.filter(event => 
        event.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        event.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
        event.location.toLowerCase().includes(searchQuery.toLowerCase())
      );
    }

    if (statusFilter !== 'all') {
      filtered = filtered.filter(event => event.status === statusFilter);
    }

    setFilteredEvents(filtered);
  }, [events, searchQuery, statusFilter]);

  const getStatusColor = (status) => {
    switch (status) {
      case 'upcoming': return 'bg-blue-100 text-blue-800';
      case 'ongoing': return 'bg-yellow-100 text-yellow-800';
      case 'completed': return 'bg-green-100 text-green-800';
      case 'cancelled': return 'bg-red-100 text-red-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const getParticipantPercentage = (current, max) => {
    if (!max || max === 0) return 0;
    return Math.round((current / max) * 100);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center">
          <Loader2 className="h-12 w-12 animate-spin text-primary-600 mx-auto mb-4" />
          <p className="text-gray-600">Loading event management...</p>
        </div>
      </div>
    );
  }

  if (!isAdmin) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center">
          <Shield className="h-16 w-16 text-red-500 mx-auto mb-4" />
          <h2 className="text-2xl font-bold text-gray-900 mb-2">Access Denied</h2>
          <p className="text-gray-600">You don't have permission to access event management.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white shadow-sm border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4 py-4 sm:py-6">
            <div className="min-w-0">
              <h1 className="text-2xl sm:text-3xl font-bold text-gray-900">Event Management</h1>
              <p className="text-sm sm:text-base text-gray-600 mt-1">Oversee all platform events and activities</p>
            </div>
            <div className="flex items-center">
              <button
                onClick={loadEvents}
                className="flex items-center justify-center px-3 sm:px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
              >
                <RefreshCw className="h-4 w-4 sm:mr-2" />
                <span className="hidden sm:inline">Refresh</span>
              </button>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 sm:py-8">
        {/* Statistics */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-6 mb-4 sm:mb-8">
          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-3 sm:p-6">
            <div className="flex items-center gap-2 sm:gap-4">
              <div className="p-2 sm:p-3 bg-blue-100 rounded-full flex-shrink-0">
                <Calendar className="h-4 w-4 sm:h-6 sm:w-6 text-blue-600" />
              </div>
              <div className="min-w-0">
                <p className="text-xs sm:text-sm font-medium text-gray-600 truncate">Total Events</p>
                <p className="text-lg sm:text-2xl font-bold text-gray-900">{events.length}</p>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-3 sm:p-6">
            <div className="flex items-center gap-2 sm:gap-4">
              <div className="p-2 sm:p-3 bg-yellow-100 rounded-full flex-shrink-0">
                <Clock className="h-4 w-4 sm:h-6 sm:w-6 text-yellow-600" />
              </div>
              <div className="min-w-0">
                <p className="text-xs sm:text-sm font-medium text-gray-600 truncate">Active</p>
                <p className="text-lg sm:text-2xl font-bold text-gray-900">{events.filter(e => e.status === 'ongoing').length}</p>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-3 sm:p-6">
            <div className="flex items-center gap-2 sm:gap-4">
              <div className="p-2 sm:p-3 bg-green-100 rounded-full flex-shrink-0">
                <Users className="h-4 w-4 sm:h-6 sm:w-6 text-green-600" />
              </div>
              <div className="min-w-0">
                <p className="text-xs sm:text-sm font-medium text-gray-600 truncate">Participants</p>
                <p className="text-lg sm:text-2xl font-bold text-gray-900">
                  {Object.values(participantCounts).reduce((sum, count) => sum + count, 0)}
                </p>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-3 sm:p-6">
            <div className="flex items-center gap-2 sm:gap-4">
              <div className="p-2 sm:p-3 bg-purple-100 rounded-full flex-shrink-0">
                <BarChart3 className="h-4 w-4 sm:h-6 sm:w-6 text-purple-600" />
              </div>
              <div className="min-w-0">
                <p className="text-xs sm:text-sm font-medium text-gray-600 truncate">Avg. Attend</p>
                <p className="text-lg sm:text-2xl font-bold text-gray-900">
                  {events.length > 0 ? Math.round(Object.values(participantCounts).reduce((sum, count) => sum + count, 0) / events.length) : 0}
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Events Table */}
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Event
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Status
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Date & Time
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Location
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Participants
                  </th>
                  <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {filteredEvents.map((event) => (
                  <tr key={event.id} className="hover:bg-gray-50">
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center">
                        <div className="flex-shrink-0 h-12 w-12">
                          <img
                            className="h-12 w-12 rounded-lg object-cover"
                            src={event.image_url || 'https://via.placeholder.com/48x48'}
                            alt={event.title}
                          />
                        </div>
                        <div className="ml-4">
                          <div className="text-sm font-medium text-gray-900 line-clamp-1">
                            {event.title}
                          </div>
                          <div className="text-sm text-gray-500 line-clamp-1">
                            {event.description}
                          </div>
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${getStatusColor(event.status)}`}>
                        {event.status}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      <div className="flex items-center">
                        <Calendar className="h-4 w-4 mr-2 text-gray-400" />
                        {formatDate(event.date)}
                      </div>
                      {event.time && (
                        <div className="flex items-center text-sm text-gray-500 mt-1">
                          <Clock className="h-4 w-4 mr-2 text-gray-400" />
                          {event.time}
                        </div>
                      )}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      <div className="flex items-center">
                        <MapPin className="h-4 w-4 mr-2 text-gray-400" />
                        {event.location}
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center">
                        <div className="flex-1">
                          <div className="text-sm text-gray-900">
                            {participantCounts[event.id] || 0}/{event.max_participants || '∞'}
                          </div>
                          <div className="w-full bg-gray-200 rounded-full h-2 mt-1">
                            <div 
                              className="bg-primary-600 h-2 rounded-full transition-all duration-300"
                              style={{ width: `${getParticipantPercentage(participantCounts[event.id] || 0, event.max_participants)}%` }}
                            ></div>
                          </div>
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                      <div className="flex items-center justify-end space-x-2">
                        <button
                          onClick={() => navigate(`/events/${event.id}`)}
                          className="text-primary-600 hover:text-primary-900"
                          title="View Event"
                        >
                          <Eye className="h-4 w-4" />
                        </button>
                        <button
                          onClick={() => navigate(`/events/${event.id}/edit`)}
                          className="text-blue-600 hover:text-blue-900"
                          title="Edit Event"
                        >
                          <Edit className="h-4 w-4" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {filteredEvents.length === 0 && (
          <div className="text-center py-12">
            <Calendar className="h-12 w-12 text-gray-400 mx-auto mb-4" />
            <h3 className="text-lg font-medium text-gray-900 mb-2">No events found</h3>
            <p className="text-gray-600">Try adjusting your search or filter criteria.</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default AdminEventManagement;
