// src/app/features/events/pages/event-edit/event-edit.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { AuthService } from '../../../../core/services/auth.service';
import { EventsService, Event } from '../../../../core/services/events.service';

@Component({
  selector: 'app-event-edit',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './event-edit.component.html',
  styleUrl: './event-edit.component.css'
})
export class EventEditComponent implements OnInit {
  eventForm!: FormGroup;
  loading = true;
  saving = false;
  error: string | null = null;
  success = false;
  user: any = null;
  eventId: string = '';
  originalEvent: Event | null = null;

  categories = [
    'Academic',
    'Sports',
    'Cultural',
    'Technology',
    'Community Service',
    'Workshop',
    'Seminar',
    'Social',
    'Other'
  ];

  constructor(
    private fb: FormBuilder,
    private route: ActivatedRoute,
    public router: Router,
    private authService: AuthService,
    private eventsService: EventsService
  ) { }

  async ngOnInit() {
    this.eventId = this.route.snapshot.paramMap.get('id') || '';
    if (!this.eventId) {
      this.router.navigate(['/events']);
      return;
    }

    this.user = await this.authService.getCurrentUser();
    if (!this.user) {
      this.router.navigate(['/login']);
      return;
    }

    this.initForm();
    await this.loadEvent();
  }

  initForm() {
    this.eventForm = this.fb.group({
      title: ['', Validators.required],
      description: ['', Validators.required],
      date: ['', Validators.required],
      time: ['', Validators.required],
      end_time: [''],
      location: ['', Validators.required],
      category: ['', Validators.required],
      max_participants: [''],
      is_virtual: [false],
      virtual_link: [''],
      image_url: ['']
    });
  }

  async loadEvent() {
    try {
      this.loading = true;
      const { data, error } = await this.eventsService.getEventById(this.eventId);

      if (error) throw error;

      if (!data) {
        this.error = 'Event not found';
        return;
      }

      // Check if user owns this event
      if (data.user_id !== this.user.id) {
        this.error = 'You do not have permission to edit this event';
        return;
      }

      this.originalEvent = data;

      // Populate form with existing data
      this.eventForm.patchValue({
        title: data.title || '',
        description: data.description || '',
        date: data.date || '',
        time: data.time || '',
        end_time: data.end_time || '',
        location: data.location || '',
        category: data.category || '',
        max_participants: data.max_participants || '',
        is_virtual: data.is_virtual || false,
        virtual_link: data.virtual_link || '',
        image_url: data.image_url || ''
      });

      if (data.image_url) {
        this.imagePreview = data.image_url;
      }

    } catch (error: any) {
      console.error('Error loading event:', error);
      this.error = error.message || 'Failed to load event';
    } finally {
      this.loading = false;
    }
  }

  selectedFile: File | null = null;
  imagePreview: string | null = null;

  onFileSelected(event: any) {
    const file = event.target.files[0];
    if (file) {
      this.selectedFile = file;
      // Create preview
      const reader = new FileReader();
      reader.onload = (e) => {
        this.imagePreview = e.target?.result as string;
      };
      reader.readAsDataURL(file);
    }
  }

  async onSubmit() {
    if (this.eventForm.invalid) {
      this.markFormGroupTouched(this.eventForm);
      return;
    }

    try {
      this.saving = true;
      this.error = null;

      let imageUrl = this.eventForm.get('image_url')?.value;

      if (this.selectedFile) {
        const { publicUrl, error: uploadError } = await this.eventsService.uploadEventImage(this.selectedFile);
        if (uploadError) throw uploadError;
        imageUrl = publicUrl;
      }

      const eventData = {
        ...this.eventForm.value,
        image_url: imageUrl,
        max_participants: this.eventForm.value.max_participants ? parseInt(this.eventForm.value.max_participants) : null
      };

      const { error } = await this.eventsService.updateEvent(this.eventId, eventData);

      if (error) throw error;

      this.success = true;
      setTimeout(() => {
        this.router.navigate(['/events', this.eventId]);
      }, 1500);

    } catch (error: any) {
      console.error('Error updating event:', error);
      this.error = error.message || 'Failed to update event';
    } finally {
      this.saving = false;
    }
  }

  private markFormGroupTouched(formGroup: FormGroup) {
    Object.keys(formGroup.controls).forEach(key => {
      const control = formGroup.get(key);
      control?.markAsTouched();
    });
  }

  get f() {
    return this.eventForm.controls;
  }

  cancel() {
    this.router.navigate(['/events', this.eventId]);
  }
}

<div *ngIf="loading" class="flex items-center justify-center min-h-screen">
    <div class="text-center">
        <div class="animate-spin h-12 w-12 border-4 border-primary-600 border-t-transparent rounded-full mx-auto mb-4">
        </div>
        <p class="text-gray-600">Loading event...</p>
    </div>
</div>

<div *ngIf="error && !loading" class="flex items-center justify-center min-h-screen">
    <div class="text-center">
        <h2 class="text-xl font-semibold text-gray-900 mb-2">Error</h2>
        <p class="text-gray-600 mb-4">{{ error }}</p>
        <button (click)="router.navigate(['/events'])" class="btn-primary">Back to Events</button>
    </div>
</div>

<div *ngIf="success" class="flex items-center justify-center min-h-screen">
    <div class="text-center">
        <svg class="h-12 w-12 text-green-500 mx-auto mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" stroke-width="2" />
        </svg>
        <h2 class="text-xl font-semibold text-gray-900 mb-2">Event Updated!</h2>
        <p class="text-gray-600">Redirecting...</p>
    </div>
</div>

<div *ngIf="!loading && !error && !success" class="max-w-4xl mx-auto py-8 px-4">
    <div class="mb-8">
        <div class="flex items-center gap-4 mb-4">
            <button (click)="cancel()" class="p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-100 rounded-lg">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none">
                    <path d="M19 12H5M12 19l-7-7 7-7" stroke="currentColor" stroke-width="2" />
                </svg>
            </button>
            <div>
                <h1 class="text-3xl font-bold text-gray-900">Edit Event</h1>
                <p class="text-gray-600 mt-1">Update your event details</p>
            </div>
        </div>
    </div>

    <form [formGroup]="eventForm" (ngSubmit)="onSubmit()"
        class="bg-white rounded-lg shadow-sm border border-gray-200 p-6 space-y-6">
        <!-- Title -->
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">Event Title *</label>
            <input type="text" formControlName="title"
                class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                placeholder="Enter event title" />
            <p *ngIf="f['title'].touched && f['title'].errors?.['required']" class="mt-1 text-sm text-red-600">
                Title is required
            </p>
        </div>

        <!-- Description -->
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">Description *</label>
            <textarea formControlName="description" rows="4"
                class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                placeholder="Describe your event"></textarea>
            <p *ngIf="f['description'].touched && f['description'].errors?.['required']"
                class="mt-1 text-sm text-red-600">
                Description is required
            </p>
        </div>

        <!-- Date and Time -->
        <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-2">Date *</label>
                <input type="date" formControlName="date"
                    class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500" />
            </div>
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-2">Start Time *</label>
                <input type="time" formControlName="time"
                    class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500" />
            </div>
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-2">End Time</label>
                <input type="time" formControlName="end_time"
                    class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500" />
            </div>
        </div>

        <!-- Location -->
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">Location *</label>
            <input type="text" formControlName="location"
                class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                placeholder="Event location or venue" />
        </div>

        <!-- Category and Max Participants -->
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-2">Category *</label>
                <select formControlName="category"
                    class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500">
                    <option value="">Select category</option>
                    <option *ngFor="let category of categories" [value]="category">{{ category }}</option>
                </select>
            </div>
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-2">Max Participants</label>
                <input type="number" formControlName="max_participants"
                    class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                    placeholder="Leave empty for unlimited" />
            </div>
        </div>

        <!-- Virtual Event -->
        <div class="flex items-center">
            <input type="checkbox" formControlName="is_virtual" id="is_virtual"
                class="h-4 w-4 text-primary-600 focus:ring-primary-500 border-gray-300 rounded" />
            <label for="is_virtual" class="ml-2 block text-sm text-gray-700">
                This is a virtual event
            </label>
        </div>

        <!-- Virtual Link -->
        <div *ngIf="eventForm.get('is_virtual')?.value">
            <label class="block text-sm font-medium text-gray-700 mb-2">Virtual Meeting Link</label>
            <input type="url" formControlName="virtual_link"
                class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                placeholder="https://meet.google.com/..." />
        </div>

        <!-- Image Upload -->
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">Event Image (optional)</label>

            <div class="flex flex-col gap-4">
                <div *ngIf="imagePreview"
                    class="relative w-full max-w-sm h-48 rounded-lg overflow-hidden border border-gray-200 bg-gray-50">
                    <img [src]="imagePreview" class="w-full h-full object-contain">
                    <button type="button"
                        (click)="selectedFile = null; imagePreview = null; eventForm.get('image_url')?.setValue('')"
                        class="absolute top-2 right-2 bg-red-600 text-white p-1 rounded-full hover:bg-red-700 transition-colors shadow-sm">
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                            stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                            <line x1="18" y1="6" x2="6" y2="18"></line>
                            <line x1="6" y1="6" x2="18" y2="18"></line>
                        </svg>
                    </button>
                </div>

                <div class="flex items-center justify-center w-full" *ngIf="!imagePreview">
                    <label for="dropzone-file-edit"
                        class="flex flex-col items-center justify-center w-full h-32 border-2 border-gray-300 border-dashed rounded-lg cursor-pointer bg-gray-50 hover:bg-gray-100">
                        <div class="flex flex-col items-center justify-center pt-5 pb-6">
                            <svg class="w-8 h-8 mb-4 text-gray-500" aria-hidden="true"
                                xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 16">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                    stroke-width="2"
                                    d="M13 13h3a3 3 0 0 0 0-6h-.025A5.56 5.56 0 0 0 16 6.5 5.5 5.5 0 0 0 5.207 5.021C5.137 5.017 5.071 5 5 5a4 4 0 0 0 0 8h2.167M10 15V6m0 0L8 8m2-2 2 2" />
                            </svg>
                            <p class="mb-2 text-sm text-gray-500"><span class="font-semibold">Click to upload</span> or
                                drag and drop</p>
                            <p class="text-xs text-gray-500">SVG, PNG, JPG or GIF (MAX. 5MB)</p>
                        </div>
                        <input id="dropzone-file-edit" type="file" class="hidden" (change)="onFileSelected($event)"
                            accept="image/*" />
                    </label>
                </div>
            </div>
        </div>

        <!-- Action Buttons -->
        <div class="flex items-center gap-4 pt-4 border-t border-gray-200">
            <button type="submit" [disabled]="saving" class="btn-primary">
                <span *ngIf="!saving">Save Changes</span>
                <span *ngIf="saving">Saving...</span>
            </button>
            <button type="button" (click)="cancel()" [disabled]="saving" class="btn-secondary">
                Cancel
            </button>
        </div>
    </form>
</div>

// src-react-backup/pages/EventEdit.js
import React, { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { 
  Calendar, 
  MapPin, 
  Clock, 
  Users, 
  Tag, 
  Image, 
  Upload, 
  Sparkles,
  Save,
  Eye,
  X,
  Loader2,
  CheckCircle,
  ArrowLeft
} from 'lucide-react';
import { auth } from '../lib/supabase';
import { eventsService } from '../services/eventsService';
import { storageService } from '../services/storageService';
import { statusService } from '../services/statusService';
import LocationSearch from '../components/LocationSearch';

const EventEdit = () => {
  const navigate = useNavigate();
  const { id } = useParams();
  const [formData, setFormData] = useState({
    title: '',
    description: '',
    date: '',
    timeHour: '09',
    timeMinute: '00',
    timePeriod: 'AM',
    endTimeHour: '11',
    endTimeMinute: '00',
    endTimePeriod: 'AM',
    location: '',
    maxParticipants: '',
    category: '',
    tags: [],
    image: null,
    isVirtual: false,
    virtualLink: '',
    requirements: '',
    contactEmail: '',
    contactPhone: ''
  });

  const [aiSuggestions, setAiSuggestions] = useState([
    'Consider adding networking breaks for better engagement',
    'Based on similar events, 2-4 PM has highest attendance',
    'Include interactive elements like Q&A sessions',
    'Central locations see 25% higher registration rates'
  ]);

  const [currentStep, setCurrentStep] = useState(1);
  const [previewMode, setPreviewMode] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(false);
  const [user, setUser] = useState(null);
  const [imagePreview, setImagePreview] = useState(null);
  const [imageUploading, setImageUploading] = useState(false);
  const [originalEventDate, setOriginalEventDate] = useState(null);

  // Get tomorrow's date in YYYY-MM-DD format for minimum date
  const getTomorrowDate = () => {
    const tomorrow = new Date();
    tomorrow.setDate(tomorrow.getDate() + 1);
    return tomorrow.toISOString().split('T')[0];
  };

  // Get minimum allowed date for editing
  // If original event date is today or past, allow keeping it, otherwise require tomorrow
  const getMinDate = () => {
    if (!originalEventDate) return getTomorrowDate();
    
    const original = new Date(originalEventDate);
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    original.setHours(0, 0, 0, 0);
    
    // If original date is today or past, allow it, otherwise require tomorrow
    if (original <= today) {
      return originalEventDate;
    }
    return getTomorrowDate();
  };

  const categories = [
    'Academic Conference',
    'Tech Summit',
    'Community Event',
    'Workshop',
    'Seminar',
    'Networking',
    'Cultural Event',
    'Sports Event'
  ];

  // Load event data
  useEffect(() => {
    const loadEventData = async () => {
      try {
        setLoading(true);
        
        // Get current user
        const { user } = await auth.getCurrentUser();
        if (!user) {
          navigate('/login');
          return;
        }
        setUser(user);

        // Load event data
        const { data: event, error } = await eventsService.getEventById(id);
        if (error) throw error;

        if (!event) {
          setError('Event not found');
          return;
        }

        // Check if user owns this event
        if (event.user_id !== user.id) {
          setError('You do not have permission to edit this event');
          return;
        }

        // Parse start time into hour/minute/period
        let timeHour = '09';
        let timeMinute = '00';
        let timePeriod = 'AM';
        
        if (event.time) {
          // Handle formats like "09:00 AM", "14:00", "2:30 PM"
          const timeStr = event.time.trim();
          const ampmMatch = timeStr.match(/(\d{1,2}):(\d{2})\s*(AM|PM)/i);
          const militaryMatch = timeStr.match(/^(\d{1,2}):(\d{2})$/);
          
          if (ampmMatch) {
            timeHour = ampmMatch[1].padStart(2, '0');
            timeMinute = ampmMatch[2];
            timePeriod = ampmMatch[3].toUpperCase();
          } else if (militaryMatch) {
            let hour = parseInt(militaryMatch[1], 10);
            timeMinute = militaryMatch[2];
            if (hour === 0) {
              timeHour = '12';
              timePeriod = 'AM';
            } else if (hour < 12) {
              timeHour = hour.toString().padStart(2, '0');
              timePeriod = 'AM';
            } else if (hour === 12) {
              timeHour = '12';
              timePeriod = 'PM';
            } else {
              timeHour = (hour - 12).toString().padStart(2, '0');
              timePeriod = 'PM';
            }
          }
        }

        // Parse end time into hour/minute/period
        let endTimeHour = '11';
        let endTimeMinute = '00';
        let endTimePeriod = 'AM';
        
        if (event.end_time) {
          // Handle formats like "09:00 AM", "14:00", "2:30 PM"
          const timeStr = event.end_time.trim();
          const ampmMatch = timeStr.match(/(\d{1,2}):(\d{2})\s*(AM|PM)/i);
          const militaryMatch = timeStr.match(/^(\d{1,2}):(\d{2})$/);
          
          if (ampmMatch) {
            endTimeHour = ampmMatch[1].padStart(2, '0');
            endTimeMinute = ampmMatch[2];
            endTimePeriod = ampmMatch[3].toUpperCase();
          } else if (militaryMatch) {
            let hour = parseInt(militaryMatch[1], 10);
            endTimeMinute = militaryMatch[2];
            if (hour === 0) {
              endTimeHour = '12';
              endTimePeriod = 'AM';
            } else if (hour < 12) {
              endTimeHour = hour.toString().padStart(2, '0');
              endTimePeriod = 'AM';
            } else if (hour === 12) {
              endTimeHour = '12';
              endTimePeriod = 'PM';
            } else {
              endTimeHour = (hour - 12).toString().padStart(2, '0');
              endTimePeriod = 'PM';
            }
          }
        }

        // Store original event date for validation
        setOriginalEventDate(event.date || '');

        // Populate form with existing data
        setFormData({
          title: event.title || '',
          description: event.description || '',
          date: event.date || '',
          timeHour,
          timeMinute,
          timePeriod,
          endTimeHour,
          endTimeMinute,
          endTimePeriod,
          location: event.location || '',
          maxParticipants: event.max_participants || '',
          category: event.category || '',
          tags: event.tags || [],
          image: event.image_url ? event.image_url : null,
          isVirtual: event.is_virtual || false,
          virtualLink: event.virtual_link || '',
          requirements: event.requirements || '',
          contactEmail: event.contact_email || '',
          contactPhone: event.contact_phone || ''
        });

        if (event.image_url) {
          setImagePreview(event.image_url);
        }

      } catch (error) {
        console.error('Error loading event:', error);
        setError(error.message || 'Failed to load event');
      } finally {
        setLoading(false);
      }
    };

    if (id) {
      loadEventData();
    }
  }, [id, navigate]);

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
  };

  const handleTagAdd = (tag) => {
    if (tag && !formData.tags.includes(tag)) {
      setFormData(prev => ({
        ...prev,
        tags: [...prev.tags, tag]
      }));
    }
  };

  const handleTagRemove = (tagToRemove) => {
    setFormData(prev => ({
      ...prev,
      tags: prev.tags.filter(tag => tag !== tagToRemove)
    }));
  };

  const handleImageUpload = async (e) => {
    const file = e.target.files[0];
    if (!file) return;

    if (file.size > 5 * 1024 * 1024) {
      setError('Image size must be less than 5MB');
      return;
    }

    setImageUploading(true);
    try {
      const imageUrl = await storageService.uploadEventImage(file, user.id);
      setFormData(prev => ({ ...prev, image: imageUrl }));
      setImagePreview(imageUrl);
    } catch (error) {
      console.error('Error uploading image:', error);
      setError('Failed to upload image');
    } finally {
      setImageUploading(false);
    }
  };

  const handleSave = async () => {
    try {
      setSaving(true);
      setError(null);

      // Validate required fields
      if (!formData.title || !formData.date) {
        setError('Title and date are required');
        return;
      }

      // Validate date is not in the past (unless it's the original date)
      const selectedDate = new Date(formData.date);
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      selectedDate.setHours(0, 0, 0, 0);
      
      const isOriginalDate = originalEventDate && formData.date === originalEventDate;
      const originalDate = originalEventDate ? new Date(originalEventDate) : null;
      if (originalDate) originalDate.setHours(0, 0, 0, 0);
      
      // If changing the date, it must be tomorrow or later
      // If keeping the original date, allow it even if it's today or past
      if (!isOriginalDate && selectedDate <= today) {
        setError('Event date must be tomorrow or later. You cannot schedule events for today or past dates.');
        return;
      }

      // Convert AM/PM start time to 24-hour format for database storage
      let hour24 = parseInt(formData.timeHour, 10);
      if (formData.timePeriod === 'PM' && hour24 !== 12) {
        hour24 += 12;
      } else if (formData.timePeriod === 'AM' && hour24 === 12) {
        hour24 = 0;
      }
      const formattedTime = `${hour24.toString().padStart(2, '0')}:${formData.timeMinute}`;

      // Convert AM/PM end time to 24-hour format for database storage
      let endHour24 = parseInt(formData.endTimeHour, 10);
      if (formData.endTimePeriod === 'PM' && endHour24 !== 12) {
        endHour24 += 12;
      } else if (formData.endTimePeriod === 'AM' && endHour24 === 12) {
        endHour24 = 0;
      }
      const formattedEndTime = `${endHour24.toString().padStart(2, '0')}:${formData.endTimeMinute}`;

      // Prepare event data
      const eventData = {
        title: formData.title,
        description: formData.description,
        date: formData.date,
        time: formattedTime,
        end_time: formattedEndTime,
        location: formData.location,
        max_participants: parseInt(formData.maxParticipants) || null,
        category: formData.category,
        tags: formData.tags,
        image_url: formData.image,
        is_virtual: formData.isVirtual,
        virtual_link: formData.virtualLink,
        requirements: formData.requirements,
        contact_email: formData.contactEmail,
        contact_phone: formData.contactPhone
      };

      // Update event
      const { error } = await eventsService.updateEvent(id, eventData);
      if (error) throw error;

      setSuccess(true);
      setTimeout(() => {
        navigate('/events');
      }, 1500);

    } catch (error) {
      console.error('Error updating event:', error);
      setError(error.message || 'Failed to update event');
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center">
          <Loader2 className="h-12 w-12 animate-spin mx-auto mb-4 text-primary-600" />
          <p className="text-gray-600">Loading event...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center">
          <X className="h-12 w-12 text-red-500 mx-auto mb-4" />
          <h2 className="text-xl font-semibold text-gray-900 mb-2">Error</h2>
          <p className="text-gray-600 mb-4">{error}</p>
          <button
            onClick={() => navigate('/events')}
            className="btn-primary"
          >
            Back to Events
          </button>
        </div>
      </div>
    );
  }

  if (success) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center">
          <CheckCircle className="h-12 w-12 text-green-500 mx-auto mb-4" />
          <h2 className="text-xl font-semibold text-gray-900 mb-2">Event Updated!</h2>
          <p className="text-gray-600">Redirecting to events page...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="mb-6 sm:mb-8">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
            <div className="flex items-center space-x-3 sm:space-x-4 min-w-0">
              <button
                onClick={() => navigate('/events')}
                className="p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-100 rounded-lg transition-colors flex-shrink-0"
              >
                <ArrowLeft size={20} />
              </button>
              <div className="min-w-0">
                <h1 className="text-2xl sm:text-3xl font-bold text-gray-900 break-words">Edit Event</h1>
                <p className="text-sm sm:text-base text-gray-600 mt-1">Update your event details</p>
              </div>
            </div>
            
            <div className="flex items-center gap-2 sm:gap-3 pl-11 sm:pl-0">
              {/* Mobile: Icon-only Preview button */}
              <button
                onClick={() => setPreviewMode(!previewMode)}
                className={`sm:hidden p-2.5 rounded-lg font-medium transition-colors ${
                  previewMode 
                    ? 'bg-primary-600 text-white' 
                    : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                }`}
                title={previewMode ? 'Edit Mode' : 'Preview'}
              >
                <Eye size={18} />
              </button>
              
              {/* Desktop: Full Preview button */}
              <button
                onClick={() => setPreviewMode(!previewMode)}
                className={`hidden sm:flex items-center px-4 py-2 rounded-lg font-medium transition-colors ${
                  previewMode 
                    ? 'bg-primary-600 text-white' 
                    : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                }`}
              >
                <Eye size={16} className="mr-2" />
                {previewMode ? 'Edit Mode' : 'Preview'}
              </button>
              
              {/* Mobile: Icon-only Save button */}
              <button
                onClick={handleSave}
                disabled={saving}
                className="sm:hidden btn-primary p-2.5 flex items-center justify-center"
                title="Save Changes"
              >
                {saving ? (
                  <Loader2 size={18} className="animate-spin" />
                ) : (
                  <Save size={18} />
                )}
              </button>
              
              {/* Desktop: Full Save button */}
              <button
                onClick={handleSave}
                disabled={saving}
                className="hidden sm:flex btn-primary items-center"
              >
                {saving ? (
                  <Loader2 size={16} className="animate-spin mr-2" />
                ) : (
                  <Save size={16} className="mr-2" />
                )}
                {saving ? 'Saving...' : 'Save Changes'}
              </button>
            </div>
          </div>
        </div>

        {/* Error Message */}
        {error && (
          <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg">
            <div className="flex">
              <X className="h-5 w-5 text-red-400 mr-2" />
              <p className="text-red-800">{error}</p>
            </div>
          </div>
        )}

        {/* Form Content */}
        <div className="bg-white rounded-lg shadow-sm border border-gray-200">
          {/* Basic Information */}
          <div className="p-4 sm:p-6 border-b border-gray-200">
            <h2 className="text-lg sm:text-xl font-semibold text-gray-900 mb-4">Basic Information</h2>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="md:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Event Title *
                </label>
                <input
                  type="text"
                  name="title"
                  value={formData.title}
                  onChange={handleInputChange}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                  placeholder="Enter event title"
                />
              </div>
              
              <div className="md:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Description
                </label>
                <textarea
                  name="description"
                  value={formData.description}
                  onChange={handleInputChange}
                  rows={4}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                  placeholder="Describe your event..."
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  <Calendar className="inline mr-1" size={16} />
                  Date *
                </label>
                <input
                  type="date"
                  name="date"
                  value={formData.date}
                  onChange={handleInputChange}
                  min={getMinDate()}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                />
                <p className="mt-1 text-xs text-gray-500">
                  {originalEventDate && (() => {
                    const original = new Date(originalEventDate);
                    const today = new Date();
                    today.setHours(0, 0, 0, 0);
                    original.setHours(0, 0, 0, 0);
                    if (original <= today) {
                      return 'You can keep the existing date, but cannot change to a past date';
                    }
                    return 'Date must be tomorrow or later';
                  })()}
                  {!originalEventDate && 'Date must be tomorrow or later'}
                </p>
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  <Clock className="inline mr-1" size={16} />
                  Start Time
                </label>
                <div className="flex flex-wrap sm:flex-nowrap gap-2">
                  <select
                    name="timeHour"
                    value={formData.timeHour}
                    onChange={handleInputChange}
                    className="px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent flex-1 min-w-[60px] sm:w-20 sm:flex-initial"
                  >
                    {['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12'].map(hour => (
                      <option key={hour} value={hour}>{hour}</option>
                    ))}
                  </select>
                  <span className="flex items-center text-gray-500 font-medium">:</span>
                  <select
                    name="timeMinute"
                    value={formData.timeMinute}
                    onChange={handleInputChange}
                    className="px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent flex-1 min-w-[60px] sm:w-20 sm:flex-initial"
                  >
                    {['00', '15', '30', '45'].map(minute => (
                      <option key={minute} value={minute}>{minute}</option>
                    ))}
                  </select>
                  <select
                    name="timePeriod"
                    value={formData.timePeriod}
                    onChange={handleInputChange}
                    className="px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent flex-1 min-w-[60px] sm:w-20 sm:flex-initial"
                  >
                    <option value="AM">AM</option>
                    <option value="PM">PM</option>
                  </select>
                </div>
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  <Clock className="inline mr-1" size={16} />
                  End Time
                </label>
                <div className="flex flex-wrap sm:flex-nowrap gap-2">
                  <select
                    name="endTimeHour"
                    value={formData.endTimeHour}
                    onChange={handleInputChange}
                    className="px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent flex-1 min-w-[60px] sm:w-20 sm:flex-initial"
                  >
                    {['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12'].map(hour => (
                      <option key={hour} value={hour}>{hour}</option>
                    ))}
                  </select>
                  <span className="flex items-center text-gray-500 font-medium">:</span>
                  <select
                    name="endTimeMinute"
                    value={formData.endTimeMinute}
                    onChange={handleInputChange}
                    className="px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent flex-1 min-w-[60px] sm:w-20 sm:flex-initial"
                  >
                    {['00', '15', '30', '45'].map(minute => (
                      <option key={minute} value={minute}>{minute}</option>
                    ))}
                  </select>
                  <select
                    name="endTimePeriod"
                    value={formData.endTimePeriod}
                    onChange={handleInputChange}
                    className="px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent flex-1 min-w-[60px] sm:w-20 sm:flex-initial"
                  >
                    <option value="AM">AM</option>
                    <option value="PM">PM</option>
                  </select>
                </div>
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  <MapPin className="inline mr-1" size={16} />
                  Location <span className="text-xs text-gray-500 font-normal">(Philippines only)</span>
                </label>
                <LocationSearch
                  value={formData.location}
                  onChange={(location) => setFormData({ ...formData, location })}
                  placeholder="Search for specific venues, buildings, or addresses..."
                />
                <p className="mt-2 text-xs text-gray-500">
                  Start typing to search for specific venues, buildings, or addresses (e.g., "SM Megamall", "Ayala Center", "123 Rizal Avenue").
                </p>
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  <Users className="inline mr-1" size={16} />
                  Max Participants
                </label>
                <input
                  type="number"
                  name="maxParticipants"
                  value={formData.maxParticipants}
                  onChange={handleInputChange}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                  placeholder="Maximum attendees"
                />
              </div>
            </div>
          </div>

          {/* Additional Details */}
          <div className="p-4 sm:p-6">
            <h2 className="text-lg sm:text-xl font-semibold text-gray-900 mb-4">Additional Details</h2>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Category
                </label>
                <select
                  name="category"
                  value={formData.category}
                  onChange={handleInputChange}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                >
                  <option value="">Select category</option>
                  {categories.map(category => (
                    <option key={category} value={category}>{category}</option>
                  ))}
                </select>
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Contact Email
                </label>
                <input
                  type="email"
                  name="contactEmail"
                  value={formData.contactEmail}
                  onChange={handleInputChange}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                  placeholder="contact@example.com"
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Contact Phone
                </label>
                <input
                  type="tel"
                  name="contactPhone"
                  value={formData.contactPhone}
                  onChange={handleInputChange}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                  placeholder="+1 (555) 123-4567"
                />
              </div>
              
              <div className="md:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Requirements
                </label>
                <textarea
                  name="requirements"
                  value={formData.requirements}
                  onChange={handleInputChange}
                  rows={3}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                  placeholder="Any special requirements or prerequisites..."
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default EventEdit;
