// src-react-backup/pages/Dashboard.js
import React, { useState, useEffect } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { 
  Calendar, 
  Users, 
  TrendingUp, 
  Clock, 
  BarChart3,
  Eye,
  Edit,
  Trash2
} from 'lucide-react';
import { auth } from '../lib/supabase';
import { dashboardService } from '../services/dashboardService';
import { scheduleService } from '../services/scheduleService';
import AIRecommendations from '../components/AIRecommendations';
import UserSchedule from '../components/UserSchedule';
import LoadingSpinner from '../components/LoadingSpinner';

const Dashboard = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const [activeTab, setActiveTab] = useState('overview');
  const [user, setUser] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);

  // Real data state
  const [stats, setStats] = useState([]);
  const [allEvents, setAllEvents] = useState([]);
  const [insights, setInsights] = useState([]);
  const [scheduleData, setScheduleData] = useState([]);
  const [dataLoading, setDataLoading] = useState(false);

  // Handle scroll to section when hash is present
  useEffect(() => {
    if (location.hash === '#my-schedule' && !isLoading) {
      // Small delay to ensure content is rendered
      setTimeout(() => {
        const element = document.getElementById('my-schedule');
        if (element) {
          element.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }
      }, 100);
    }
  }, [location.hash, isLoading]);

  // Load dashboard data
  useEffect(() => {
    const loadDashboardData = async () => {
      try {
        const { user: currentUser } = await auth.getCurrentUser();
        setUser(currentUser);
        
        // If no user, redirect to login
        if (!currentUser) {
          navigate('/login');
          return;
        }

        // Load all dashboard data - pass user directly since state isn't updated yet
        await loadData(currentUser);
      } catch (error) {
        console.error('Error getting user:', error);
        navigate('/login');
      } finally {
        setIsLoading(false);
      }
    };

    loadDashboardData();

    // Listen for auth state changes
    const { data: { subscription } } = auth.onAuthStateChange((event, session) => {
      setUser(session?.user || null);
      
      if (!session?.user) {
        navigate('/login');
      } else {
        // Reload data when user changes - pass user directly
        loadData(session.user);
      }
    });

    return () => subscription.unsubscribe();
  }, [navigate]);

  const getChangeDisplay = (change, suffix = '%') => {
    if (change === null || change === undefined) {
      return {
        label: '—',
        className: 'text-gray-400'
      };
    }

    const numericChange = Number(change);
    if (Number.isNaN(numericChange)) {
      return {
        label: '—',
        className: 'text-gray-400'
      };
    }

    const sign = numericChange > 0 ? '+' : numericChange < 0 ? '' : '';
    const className = numericChange > 0
      ? 'text-green-600'
      : numericChange < 0
        ? 'text-red-600'
        : 'text-gray-500';

    return {
      label: `${sign}${numericChange}${suffix}`,
      className
    };
  };

  const loadData = async (currentUser = null) => {
    try {
      setError(null);
      setDataLoading(true);

      // Use passed user or fall back to state
      const activeUser = currentUser || user;
      
      if (!activeUser) {
        console.error('No user available for loading data');
        return;
      }

      // Get user role for stats and schedule
      const userRole = activeUser.user_metadata?.role || 'user';
      
      console.log('Loading dashboard data for user:', activeUser.id, 'role:', userRole);

      // Load all data in parallel
      const [
        dashboardStats,
        allEventsData,
        insightsData,
        scheduleDataResult
      ] = await Promise.all([
        dashboardService.getDashboardStats(activeUser.id, userRole),
        dashboardService.getAllEvents(userRole),
        dashboardService.getDashboardInsights(activeUser.id, userRole),
        scheduleService.getUserSchedule(activeUser.id, userRole)
      ]);
      
      console.log('Schedule data loaded:', scheduleDataResult);

      // Format stats for display based on user role
      const isOrganizer = userRole === 'Organizer' || userRole === 'organizer';
      const isAdmin = userRole === 'Administrator' || userRole === 'Admin';
      
      let formattedStats;
      
      if (isOrganizer || isAdmin) {
        // Stats for organizers/admins - events they created
        formattedStats = [
          { 
            name: 'My Events', 
            value: dashboardStats.totalEvents.toString(), 
            change: getChangeDisplay(dashboardStats.eventGrowth), 
            icon: Calendar, 
            color: 'blue' 
          },
          { 
            name: 'Total Registrations', 
            value: dashboardStats.totalParticipants.toLocaleString(), 
            change: getChangeDisplay(dashboardStats.participantGrowth), 
            icon: Users, 
            color: 'green' 
          },
          { 
            name: 'Attendance Rate', 
            value: `${dashboardStats.engagementRate}%`, 
            change: getChangeDisplay(dashboardStats.engagementChange, 'pp'), 
            icon: TrendingUp, 
            color: 'purple' 
          },
          { 
            name: 'Upcoming Events', 
            value: dashboardStats.upcomingEvents.toString(), 
            change: getChangeDisplay(dashboardStats.upcomingChange), 
            icon: Clock, 
            color: 'orange' 
          },
        ];
      } else {
        // Stats for regular users - events they're registered for
        formattedStats = [
          { 
            name: 'Registered Events', 
            value: dashboardStats.registeredEvents.toString(), 
            change: getChangeDisplay(null), 
            icon: Calendar, 
            color: 'blue' 
          },
          { 
            name: 'Events Attended', 
            value: dashboardStats.attendedEvents.toString(), 
            change: getChangeDisplay(null), 
            icon: Users, 
            color: 'green' 
          },
          { 
            name: 'Upcoming Events', 
            value: dashboardStats.upcomingRegistrations.toString(), 
            change: getChangeDisplay(null), 
            icon: Clock, 
            color: 'orange' 
          },
        ];
      }

      setStats(formattedStats);
      setAllEvents(allEventsData);
      setInsights(insightsData);
      setScheduleData(scheduleDataResult);

    } catch (error) {
      console.error('Error loading dashboard data:', error);
      setError('Failed to load dashboard data. Please try again.');
    } finally {
      setDataLoading(false);
    }
  };

  // Show loading state while checking authentication
  if (isLoading) {
    return <LoadingSpinner fullScreen size="lg" text="Loading dashboard..." />;
  }

  return (
    <div className="space-y-4 sm:space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-2 sm:gap-0">
        <div className="min-w-0 flex-1">
          <h1 className="text-2xl sm:text-3xl font-bold text-gray-900 break-words">Dashboard</h1>
          <p className="text-sm sm:text-base text-gray-600 mt-1 break-words">
            Welcome back{user?.user_metadata?.first_name ? `, ${user.user_metadata.first_name}` : ''}! Here's what's happening with events around you.
          </p>
        </div>
      </div>

      {/* Error Message */}
      {error && (
        <div className="bg-red-50 border border-red-200 rounded-lg p-4">
          <p className="text-red-800">{error}</p>
          <button 
            onClick={loadData}
            className="mt-2 text-red-600 hover:text-red-800 underline"
          >
            Try again
          </button>
        </div>
      )}

      {/* Stats Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6 gap-4 sm:gap-6">
        {stats.map((stat) => (
          <div key={stat.name} className="card min-w-0">
            <div className="flex items-center justify-between gap-2">
              <div className="min-w-0 flex-1">
                <p className="text-xs sm:text-sm font-medium text-gray-600 truncate">{stat.name}</p>
                <p className="text-xl sm:text-2xl font-bold text-gray-900 truncate">{stat.value}</p>
                <p className={`text-xs sm:text-sm ${stat.change.className} truncate`}>{stat.change.label}</p>
              </div>
              <div className={`p-2 sm:p-3 rounded-full bg-${stat.color}-100 flex-shrink-0`}>
                <stat.icon className={`text-${stat.color}-600`} size={20} />
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Tabs */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
        <div className="border-b border-gray-200">
          <nav className="flex overflow-x-auto scrollbar-hide px-4 sm:px-6">
            <div className="flex space-x-4 sm:space-x-8 min-w-max">
              {['overview', 'events', 'insights'].map((tab) => (
                <button
                  key={tab}
                  onClick={() => setActiveTab(tab)}
                  className={`py-4 px-1 border-b-2 font-medium text-sm capitalize whitespace-nowrap ${
                    activeTab === tab
                      ? 'border-primary-500 text-primary-600'
                      : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
                  }`}
                >
                  {tab}
                </button>
              ))}
            </div>
          </nav>
        </div>

        <div className="p-4 sm:p-6">
          {activeTab === 'overview' && (
            <>
              {/* AI Recommendations */}
              <div className="mb-4 sm:mb-6">
                <AIRecommendations user={user} />
              </div>

              {/* User Schedule */}
              <div id="my-schedule">
                <UserSchedule scheduleData={scheduleData} user={user} />
              </div>
            </>
          )}

          {activeTab === 'events' && (() => {
            const userRole = user?.user_metadata?.role || 'user';
            const isOrganizerOrAdmin = userRole === 'Organizer' || userRole === 'organizer' || userRole === 'Administrator' || userRole === 'Admin';
            
            return (
              <div className="space-y-4">
                <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-3 sm:gap-0">
                  <h3 className="text-base sm:text-lg font-semibold text-gray-900 break-words">
                    {isOrganizerOrAdmin ? 'My Created Events' : 'My Registered Events'}
                  </h3>
                  <div className="flex flex-wrap gap-2">
                    <button className="btn-secondary text-sm">Filter</button>
                    <button className="btn-primary text-sm">Export</button>
                  </div>
                </div>
                
                {error && (
                  <div className="bg-red-50 border border-red-200 rounded-lg p-4">
                    <p className="text-red-800">{error}</p>
                    <button 
                      onClick={loadData}
                      className="mt-2 text-red-600 hover:text-red-800 underline"
                    >
                      Try again
                    </button>
                  </div>
                )}

                <div className="overflow-x-auto -mx-4 sm:mx-0">
                  <div className="inline-block min-w-full align-middle px-4 sm:px-0">
                    <table className="min-w-full divide-y divide-gray-200">
                      <thead className="bg-gray-50">
                        <tr>
                          <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Event</th>
                          <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider hidden sm:table-cell">Date</th>
                          <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider hidden md:table-cell">
                            {isOrganizerOrAdmin ? 'Participants' : 'Attendees'}
                          </th>
                          <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                          <th className="px-3 sm:px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
                        </tr>
                      </thead>
                      <tbody className="bg-white divide-y divide-gray-200">
                        {allEvents.length > 0 ? (
                          allEvents.map((event) => (
                            <tr key={event.id}>
                              <td className="px-3 sm:px-6 py-4 min-w-0">
                                <div className="text-sm font-medium text-gray-900 break-words">{event.title}</div>
                                <div className="text-xs sm:text-sm text-gray-500 break-words">{event.location}</div>
                                <div className="text-xs text-gray-500 sm:hidden mt-1">
                                  {dashboardService.formatDate(event.date)}
                                </div>
                                <div className="text-xs text-gray-500 sm:hidden mt-1">
                                  {isOrganizerOrAdmin ? 'Participants' : 'Attendees'}: {event.participants}
                                </div>
                              </td>
                              <td className="px-3 sm:px-6 py-4 text-sm text-gray-900 hidden sm:table-cell whitespace-nowrap">
                                {dashboardService.formatDate(event.date)}
                              </td>
                              <td className="px-3 sm:px-6 py-4 text-sm text-gray-900 hidden md:table-cell whitespace-nowrap">
                                {event.participants}
                              </td>
                              <td className="px-3 sm:px-6 py-4">
                                <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full whitespace-nowrap ${
                                  event.status === 'upcoming' ? 'bg-blue-100 text-blue-800' :
                                  event.status === 'ongoing' ? 'bg-green-100 text-green-800' :
                                  event.status === 'completed' ? 'bg-gray-100 text-gray-800' :
                                  'bg-red-100 text-red-800'
                                }`}>
                                  {event.status}
                                </span>
                              </td>
                              <td className="px-3 sm:px-6 py-4 text-sm font-medium">
                                <div className="flex flex-wrap gap-2">
                                  <button 
                                    onClick={() => navigate(`/events/${event.id}`)}
                                    className="text-primary-600 hover:text-primary-900"
                                    title="View Event"
                                  >
                                    <Eye size={16} />
                                  </button>
                                  {isOrganizerOrAdmin && (
                                    <>
                                      <button 
                                        onClick={() => navigate(`/events/${event.id}/edit`)}
                                        className="text-gray-600 hover:text-gray-900"
                                        title="Edit Event"
                                      >
                                        <Edit size={16} />
                                      </button>
                                      <button 
                                        className="text-red-600 hover:text-red-900"
                                        title="Delete Event"
                                      >
                                        <Trash2 size={16} />
                                      </button>
                                    </>
                                  )}
                                </div>
                              </td>
                            </tr>
                          ))
                        ) : (
                          <tr>
                            <td colSpan="5" className="px-6 py-12 text-center text-gray-500">
                              {isOrganizerOrAdmin 
                                ? 'No events found. Create your first event to get started!'
                                : 'No registered events. Browse events to find one to register for!'
                              }
                            </td>
                          </tr>
                        )}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            );
          })()}

          {activeTab === 'insights' && (
            <div>
              <h3 className="text-base sm:text-lg font-semibold text-gray-900 mb-4">Smart Insights</h3>
              {insights.length > 0 ? (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-6 gap-4 sm:gap-6">
                  {insights.map((insight, index) => (
                    <div key={index} className="card min-w-0">
                      <div className="flex items-start mb-3 gap-3">
                        <div className="p-2 bg-primary-100 rounded-lg flex-shrink-0">
                          {insight.icon === 'calendar' && <Calendar className="text-primary-600" size={20} />}
                          {insight.icon === 'trending-up' && <TrendingUp className="text-primary-600" size={20} />}
                          {insight.icon === 'clock' && <Clock className="text-primary-600" size={20} />}
                          {insight.icon === 'users' && <Users className="text-primary-600" size={20} />}
                        </div>
                        <h4 className="font-semibold text-gray-900 break-words flex-1 min-w-0">{insight.title}</h4>
                      </div>
                      <p className="text-sm text-gray-600 mb-3 break-words">{insight.description}</p>
                      <div className="bg-blue-50 p-3 rounded-lg">
                        <p className="text-sm text-blue-800 break-words">
                          <strong>Recommendation:</strong> {insight.recommendation}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-center py-8 text-gray-500">
                  <BarChart3 className="mx-auto mb-3 text-gray-400" size={32} />
                  <p>No insights available yet.</p>
                  <p className="text-sm">Create more events to generate insights!</p>
                </div>
              )}
            </div>
          )}
        </div>
      </div>

    </div>
  );
};

export default Dashboard;

// src/app/features/dashboard/pages/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../../../core/services/auth.service';
import { AuthUser } from '../../../../core/services/supabase.service';
import { DashboardService, DashboardStats, DashboardEvent, DashboardInsight } from '../../../../core/services/dashboard.service';
import { ScheduleService, ScheduleEvent } from '../../../../core/services/schedule.service';
import { UserScheduleComponent } from '../../../../shared/components/user-schedule/user-schedule.component';
import { AiRecommendationsComponent } from '../../../../shared/components/ai-recommendations/ai-recommendations.component';

@Component({
    selector: 'app-dashboard',
    standalone: true,
    imports: [CommonModule, RouterModule, UserScheduleComponent, AiRecommendationsComponent],
    templateUrl: './dashboard.component.html',
    styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent implements OnInit {
    currentUser: AuthUser | null = null;
    isSidebarCollapsed = false;
    currentPage = 'Dashboard';
    activeTab: 'overview' | 'events' | 'insights' = 'overview';

    // Data state
    stats: DashboardStats | null = null;
    allEvents: DashboardEvent[] = [];
    insights: DashboardInsight[] = [];
    scheduleData: ScheduleEvent[] = [];
    isLoading = true;
    dataLoading = false;
    error: string | null = null;

    constructor(
        private authService: AuthService,
        private router: Router,
        private dashboardService: DashboardService,
        private scheduleService: ScheduleService
    ) { }

    async ngOnInit() {
        this.currentUser = await this.authService.getCurrentUser();
        if (!this.currentUser) {
            this.router.navigate(['/login']);
            return;
        }

        // Load dashboard data
        await this.loadData();
        this.isLoading = false;
    }

    async loadData() {
        try {
            this.error = null;
            this.dataLoading = true;

            if (!this.currentUser) return;

            const userRole = this.currentUser.user_metadata?.role || 'user';

            console.log('Loading dashboard data for user:', this.currentUser.id, 'role:', userRole);

            // Load all data in parallel
            const [dashboardStats, allEventsData, insightsData, scheduleDataResult] = await Promise.all([
                this.dashboardService.getDashboardStats(this.currentUser.id, userRole),
                this.dashboardService.getAllEvents(userRole),
                this.dashboardService.getDashboardInsights(this.currentUser.id, userRole),
                this.scheduleService.getUserSchedule(this.currentUser.id, userRole)
            ]);

            console.log('Schedule data loaded:', scheduleDataResult);

            this.stats = dashboardStats;
            this.allEvents = allEventsData;
            this.insights = insightsData;
            this.scheduleData = scheduleDataResult;

        } catch (error) {
            console.error('Error loading dashboard data:', error);
            this.error = 'Failed to load dashboard data. Please try again.';
        } finally {
            this.dataLoading = false;
        }
    }

    toggleSidebar() {
        this.isSidebarCollapsed = !this.isSidebarCollapsed;
    }

    async logout() {
        const result = await this.authService.signOut();
        if (result.success) {
            this.router.navigate(['/landing']);
        }
    }

    navigateTo(page: string, route: string) {
        this.currentPage = page;
        this.router.navigate([route]);
    }

    setActiveTab(tab: 'overview' | 'events' | 'insights') {
        this.activeTab = tab;
    }

    getChangeDisplay(change: number | null, suffix: string = '%'): { label: string, className: string } {
        if (change === null || change === undefined) {
            return {
                label: '—',
                className: 'text-gray-400'
            };
        }

        const numericChange = Number(change);
        if (Number.isNaN(numericChange)) {
            return {
                label: '—',
                className: 'text-gray-400'
            };
        }

        const sign = numericChange > 0 ? '+' : numericChange < 0 ? '' : '';
        const className = numericChange > 0
            ? 'text-green-600'
            : numericChange < 0
                ? 'text-red-600'
                : 'text-gray-500';

        return {
            label: `${sign}${numericChange}${suffix}`,
            className
        };
    }

    formatDate(dateString: string): string {
        return this.dashboardService.formatDate(dateString);
    }

    get userDisplayName(): string {
        if (!this.currentUser) return 'User';
        const firstName = this.currentUser.user_metadata?.first_name;
        const lastName = this.currentUser.user_metadata?.last_name;
        if (firstName && lastName) {
            return `${firstName} ${lastName}`;
        }
        return this.currentUser.email || 'User';
    }

    get userRole(): string {
        return this.currentUser?.user_metadata?.role || 'User';
    }

    get isAdmin(): boolean {
        return this.authService.isAdmin;
    }

    get isOrganizerOrAdmin(): boolean {
        const role = this.currentUser?.user_metadata?.role || 'user';
        return role === 'Organizer' || role === 'organizer' || role === 'Administrator' || role === 'Admin';
    }
}


<!-- Stats Cards -->
<div class="stats-grid">
    <div class="stat-card blue">
        <div class="stat-icon">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
                <rect x="3" y="4" width="18" height="18" rx="2" stroke="currentColor" stroke-width="2" />
                <path d="M16 2v4M8 2v4M3 10h18" stroke="currentColor" stroke-width="2" />
            </svg>
        </div>
        <div class="stat-info">
            <div class="stat-label">{{ isOrganizerOrAdmin ? 'Total Events' : 'Registered Events' }}</div>
            <div class="stat-value">{{ stats?.totalEvents || 0 }}</div>
            <div class="stat-change" [ngClass]="getChangeDisplay(stats?.eventGrowth ?? null).className">
                {{ getChangeDisplay(stats?.eventGrowth ?? null).label }}
            </div>
        </div>
    </div>

    <div class="stat-card green" *ngIf="isOrganizerOrAdmin">
        <div class="stat-icon">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
                <path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2" stroke="currentColor" stroke-width="2" />
                <circle cx="9" cy="7" r="4" stroke="currentColor" stroke-width="2" />
            </svg>
        </div>
        <div class="stat-info">
            <div class="stat-label">Participants</div>
            <div class="stat-value">{{ stats?.totalParticipants || 0 }}</div>
            <div class="stat-change" [ngClass]="getChangeDisplay(stats?.participantGrowth ?? null).className">
                {{ getChangeDisplay(stats?.participantGrowth ?? null).label }}
            </div>
        </div>
    </div>

    <!-- Alternative for Regular Users -->
    <div class="stat-card green" *ngIf="!isOrganizerOrAdmin">
        <div class="stat-icon">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
                <path d="M22 11.08V12a10 10 0 11-5.93-9.14" stroke="currentColor" stroke-width="2" />
                <path d="M22 4L12 14.01l-3-3" stroke="currentColor" stroke-width="2" />
            </svg>
        </div>
        <div class="stat-info">
            <div class="stat-label">Attended Events</div>
            <div class="stat-value">{{ stats?.attendedEvents || 0 }}</div>
            <div class="stat-change neutral">
                {{ stats?.engagementRate || 0 }}% rate
            </div>
        </div>
    </div>

    <div class="stat-card purple">
        <div class="stat-icon">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
                <circle cx="12" cy="12" r="10" stroke="currentColor" stroke-width="2" />
                <path d="M12 6v6l4 2" stroke="currentColor" stroke-width="2" />
            </svg>
        </div>
        <div class="stat-info">
            <div class="stat-label">Upcoming</div>
            <div class="stat-value">{{ stats?.upcomingEvents || 0 }}</div>
            <div class="stat-change" [ngClass]="getChangeDisplay(stats?.upcomingChange ?? null).className">
                {{ getChangeDisplay(stats?.upcomingChange ?? null).label }}
            </div>
        </div>
    </div>

    <div class="stat-card orange" *ngIf="isOrganizerOrAdmin">
        <div class="stat-icon">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
                <path d="M22 11.08V12a10 10 0 11-5.93-9.14" stroke="currentColor" stroke-width="2" />
                <path d="M22 4L12 14.01l-3-3" stroke="currentColor" stroke-width="2" />
            </svg>
        </div>
        <div class="stat-info">
            <div class="stat-label">Completed</div>
            <div class="stat-value">{{ stats?.completedEvents || 0 }}</div>
            <div class="stat-change" [ngClass]="getChangeDisplay(stats?.engagementChange ?? null).className">
                {{ getChangeDisplay(stats?.engagementChange ?? null).label }}
            </div>
        </div>
    </div>

    <!-- Alternative for Regular Users -->
    <div class="stat-card orange" *ngIf="!isOrganizerOrAdmin">
        <div class="stat-icon">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
                <circle cx="12" cy="12" r="10" stroke="currentColor" stroke-width="2" />
                <line x1="12" y1="8" x2="12" y2="12" stroke="currentColor" stroke-width="2" />
                <line x1="12" y1="16" x2="12.01" y2="16" stroke="currentColor" stroke-width="2" />
            </svg>
        </div>
        <div class="stat-info">
            <div class="stat-label">Waiting List</div>
            <div class="stat-value">0</div>
            <div class="stat-change neutral">—</div>
        </div>
    </div>
</div>

<!-- Quick Actions -->
<div class="quick-actions-bar">
    <h3>Quick Actions</h3>
    <div class="action-buttons">
        <button *ngIf="isOrganizerOrAdmin" class="action-btn primary"
            (click)="navigateTo('Create Event', '/events/create')">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none">
                <circle cx="12" cy="12" r="10" stroke="currentColor" stroke-width="2" />
                <path d="M12 8v8M8 12h8" stroke="currentColor" stroke-width="2" />
            </svg>
            Create New Event
        </button>
        <button class="action-btn secondary" (click)="navigateTo('Events', '/events')">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none">
                <rect x="3" y="4" width="18" height="18" rx="2" stroke="currentColor" stroke-width="2" />
                <path d="M16 2v4M8 2v4M3 10h18" stroke="currentColor" stroke-width="2" />
            </svg>
            View All Events
        </button>
        <button *ngIf="isOrganizerOrAdmin" class="action-btn secondary" (click)="navigateTo('Analytics', '/analytics')">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none">
                <path d="M3 3v18h18" stroke="currentColor" stroke-width="2" />
                <path d="M18 17V9M13 17v-6M8 17v-3" stroke="currentColor" stroke-width="2" />
            </svg>
            View Analytics
        </button>
    </div>
</div>

<!-- Tabs -->
<div class="tabs-container">
    <div class="tabs">
        <button class="tab" [class.active]="activeTab === 'overview'" (click)="setActiveTab('overview')">
            Overview
        </button>
        <button class="tab" [class.active]="activeTab === 'events'" (click)="setActiveTab('events')">
            {{ isOrganizerOrAdmin ? 'My Events' : 'My Registrations' }}
        </button>
        <button class="tab" [class.active]="activeTab === 'insights'" (click)="setActiveTab('insights')">
            Insights
        </button>
    </div>
</div>

<!-- Tab Content -->
<div class="tab-content">
    <!-- Overview Tab -->
    <div *ngIf="activeTab === 'overview'" class="tab-pane">
        <!-- AI Event Recommendations -->
        <div class="ai-recommendations">
            <app-ai-recommendations [user]="currentUser"></app-ai-recommendations>
        </div>

        <!-- My Schedule -->
        <div class="my-schedule">
            <app-user-schedule [scheduleData]="scheduleData" [user]="currentUser" [userRole]="userRole">
            </app-user-schedule>
        </div>
    </div>

    <!-- Events Tab -->
    <div *ngIf="activeTab === 'events'" class="tab-pane">
        <div class="events-table-container">
            <div class="table-header">
                <h3>{{ isOrganizerOrAdmin ? 'My Created Events' : 'My Registered Events' }}</h3>
                <button class="filter-btn">Filter</button>
                <button class="export-btn">Export</button>
            </div>

            <div *ngIf="allEvents.length === 0" class="no-events">
                <p>No events found. {{ isOrganizerOrAdmin ? 'Create your first event to get started!' : 'Register for an
                    event to see it here.' }}</p>
                <button *ngIf="isOrganizerOrAdmin" class="mt-4 btn-primary"
                    (click)="navigateTo('Create Event', '/events/create')">Create Event</button>
                <button *ngIf="!isOrganizerOrAdmin" class="mt-4 btn-primary"
                    (click)="navigateTo('Events', '/events')">Browse Events</button>
            </div>

            <!-- Simple List/Table for Events -->
            <div *ngIf="allEvents.length > 0" class="grid gap-4">
                <div *ngFor="let event of allEvents"
                    class="bg-white p-4 rounded-lg border border-gray-200 flex justify-between items-center">
                    <div>
                        <h4 class="font-semibold text-gray-900">{{ event.title }}</h4>
                        <div class="text-sm text-gray-500 mt-1">
                            {{ formatDate(event.date) }} • {{ event.time }} • {{ event.location }}
                        </div>
                        <div *ngIf="!isOrganizerOrAdmin" class="mt-2 text-xs">
                            <span [class.text-green-600]="event.registration_status === 'registered'"
                                [class.text-blue-600]="event.registration_status === 'attended'">
                                Status: {{ event.registration_status | titlecase }}
                            </span>
                        </div>
                    </div>
                    <div class="text-right">
                        <div *ngIf="isOrganizerOrAdmin" class="text-sm font-medium text-gray-900">{{ event.participants
                            }} participants</div>
                        <div class="text-xs px-2 py-1 rounded mt-2 inline-block"
                            [class.bg-green-100]="event.status === 'upcoming'"
                            [class.text-green-800]="event.status === 'upcoming'"
                            [class.bg-blue-100]="event.status === 'ongoing'"
                            [class.text-blue-800]="event.status === 'ongoing'"
                            [class.bg-gray-100]="event.status === 'completed'"
                            [class.text-gray-800]="event.status === 'completed'">
                            {{ event.status | uppercase }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Insights Tab -->
    <div *ngIf="activeTab === 'insights'" class="tab-pane">
        <div class="insights-grid">
            <div *ngFor="let insight of insights" class="insight-card">
                <div class="insight-icon" [class.blue]="insight.icon === 'calendar'"
                    [class.green]="insight.icon === 'trending-up'" [class.purple]="insight.icon === 'clock'"
                    [class.orange]="insight.icon === 'users'">
                    <!-- Render Icons based on type -->
                    <svg *ngIf="insight.icon === 'calendar'" width="24" height="24" viewBox="0 0 24 24" fill="none">
                        <rect x="3" y="4" width="18" height="18" rx="2" stroke="currentColor" stroke-width="2" />
                    </svg>
                    <svg *ngIf="insight.icon === 'trending-up'" width="24" height="24" viewBox="0 0 24 24" fill="none">
                        <path d="M23 6l-9.5 9.5-5-5L1 18" stroke="currentColor" stroke-width="2" />
                    </svg>
                    <svg *ngIf="insight.icon === 'clock'" width="24" height="24" viewBox="0 0 24 24" fill="none">
                        <circle cx="12" cy="12" r="10" stroke="currentColor" stroke-width="2" />
                        <path d="M12 6v6l4 2" stroke="currentColor" stroke-width="2" />
                    </svg>
                    <svg *ngIf="insight.icon === 'users'" width="24" height="24" viewBox="0 0 24 24" fill="none">
                        <path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2" stroke="currentColor" stroke-width="2" />
                        <circle cx="9" cy="7" r="4" stroke="currentColor" stroke-width="2" />
                    </svg>
                </div>
                <h4>{{ insight.title }}</h4>
                <p>{{ insight.description }}</p>
                <div class="insight-recommendation" *ngIf="insight.recommendation">
                    <strong>Recommendation:</strong> {{ insight.recommendation }}
                </div>
            </div>

            <div *ngIf="insights.length === 0" class="text-center py-8 text-gray-500">
                No insights available at this time.
            </div>
        </div>
    </div>
</div>
